### ISSUE TITLE
Question : How to export model with uv animation?

### ISSUE THREAD

**Issue by unagi2152** [Parik27/DragonFF#102]
when I export model with uv animation, uv scale is set to 0.
![image](https://user-images.githubusercontent.com/86873681/124358974-8909b880-dc42-11eb-80c5-1021300875f7.png)
Exported file

![image](https://user-images.githubusercontent.com/86873681/124358932-53fd6600-dc42-11eb-828b-e12fd647905b.png)
Imported dff file

**Comment by Psycrow101** [comment]
Solved by https://github.com/Parik27/DragonFF/commit/83ef9f1360e1016d01dfef410c95681034c29fe2
