### ISSUE TITLE
Scale problem

### ISSUE THREAD

**Issue by 669344682** [Parik27/DragonFF#106]
There is nothing happening in MTA after I rescale the modell. I guess that the problem occurs in the export section, please fix that. Thanks

**Comment by Skyliner77** [comment]
You just ain't doing it right.
Always check your "transform" box, you should apply all transformations after model manipulation for them to be active after export in game. 
For example I tweaked my model a little, rotated and scaled it.
![image](https://user-images.githubusercontent.com/75580678/129475871-a6f8f1ce-72ef-4b58-aa60-446654e525a7.png)
You can see side window tracked my actions, but if I export model right now - nothing from what I did would save.
You need to apply the transformations by pressing "cntrl + a":
![image](https://user-images.githubusercontent.com/75580678/129475905-bbaecd8f-dc39-4bbd-9508-4896c576d78e.png)
Rotation and scale must be applied all the time, location in some cases:
![image](https://user-images.githubusercontent.com/75580678/129475980-cdd39853-1867-4079-8354-6462c5816515.png)
Scale should be at X: 1; Y: 1; Z: 1.
For the rotation, 0 degrees everywhere. ( I use Quaternion measurements. nvm that) 
(default XYZ) 
![image](https://user-images.githubusercontent.com/75580678/129476031-614b4552-79cd-48a5-837a-629cf0c14688.png)

**Comment by 669344682** [comment]
As Skyliner77 said, he is correct.
