### ISSUE TITLE
Custom normals not applying correctly at vehicle export.

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [Parik27/DragonFF#107]
![](https://cdn.discordapp.com/attachments/667790031913746499/863150285449986058/unknown.png)

![](https://cdn.discordapp.com/attachments/667790031913746499/863150340291690526/unknown.png)

![](https://cdn.discordapp.com/attachments/667790031913746499/863150516070907914/unknown.png)

![](https://cdn.discordapp.com/attachments/667790031913746499/863150544889577482/unknown.png)

![](https://cdn.discordapp.com/attachments/667790031913746499/863150818538422282/unknown.png)

![](https://cdn.discordapp.com/attachments/667790031913746499/863150858389028885/unknown.png)

![](https://cdn.discordapp.com/attachments/667790031913746499/863150905456721971/unknown.png)

In some places, the normals are not applied correctly at export.
Importing back the exported DFF will show the damaged areas just like in the game:
![image](https://user-images.githubusercontent.com/47691365/129245530-f648face-87b9-4168-a49e-560cc28f6a49.png)

Exporting some other format, like FBX/OBJ/DAE, and importing back will have the model showing fine, with normals applied correctly.

**Comment by Skyliner77** [comment]
Your faces probably facing the wrong direction.
![image](https://user-images.githubusercontent.com/75580678/129475589-b365552c-8a52-48d4-a43c-3cac42244bd2.png)
To fix this, first turn on face orientation. 
![image](https://user-images.githubusercontent.com/75580678/129475611-52f57521-7bee-4269-9e9b-43a585cba05b.png)
Blue = normals facing otside, red = inside.
To flip normals use "alt + n" to open normals manipulation menu, from there you can simply flip them in the directioun you need.
![image](https://user-images.githubusercontent.com/75580678/129475673-87a1ff63-a6d0-4cc3-a10e-662181fbc4d2.png)
![image](https://user-images.githubusercontent.com/75580678/129475681-6545e3cb-89b5-46c2-ab4a-1d3130e2f716.png)
![image](https://user-images.githubusercontent.com/75580678/129475685-3e52bc2d-6848-49bf-99b8-57d189d8cb13.png)
If you stubmle upon messy model, you can select all faces and use "recalculate" option to save yourself some time.

**Comment by ThePortuguesePlayer** [comment]
I want to congratulate you on the well explained tutorial and that you cared to write it (because many people won't put the care in), however, this time it's not that.
The screenshots from Blender up there have Backface Culling turned on. I always have it on. The work I do for my project is exactly in the quality control stage. I make sure everything with the models I get from the rest of my team is visually okay.

What is happening is that the verts that break ingame are part of the seams (the border zone) of their respective UV islands, and due to the DFF format not supporting more than one UV coordinate per vertex, the exporter is ripping apart the mesh at those seams and applying custom normals so the hard edges aren't visible ingame. Where the exporter is glitching is that it is not applying the normals on all of those overlapped vertices, either the newly created ones or the original is being left out and having newly generated normals, making it have a hard edge. That's what I am reporting, and I should have given this context sooner.

**Comment by Skyliner77** [comment]
If possible can you give me a model so I can look closer at it? Just DM me or sent me mail if you want it to be private.
