### ISSUE TITLE
Map importing is not working for GTA SA

### ISSUE THREAD

**Issue by fnavas00** [Parik27/DragonFF#108]
tried using map imported for GTA SA LAe2.. it imports the filenames in the outliner but not much else. At first I thought maybe the models were really small but there is literally nothing there...

btw im using blender 2.93

**Comment by PlatinMTA** [comment]
I'm having the same problem, did you find a way to get it working?

**Comment by PlatinMTA** [comment]
I thougth I had the same issue, until i selected an object and pressed the "." on the numpad.

The objects are not centered.

**Comment by Allerek** [comment]
According to official MTA Discord, it might be because some .ipl files, are in GTA3.img archive, and are binary.
https://discord.com/channels/278474088903606273/592477067766136833/882647209265471508
(You gotta be in MTA discord)

**Comment by Psycrow101** [comment]
I think it solved by https://github.com/Parik27/DragonFF/pull/308
