### ISSUE TITLE
Map Import makes all textures set to alpha

### ISSUE THREAD

**Issue by DukeVen** [Parik27/DragonFF#113]
importing a map sets all the textures to alpha.
![asd](https://user-images.githubusercontent.com/64648810/137513345-89c41f12-c16f-4919-a769-f46964d189ea.png)

**Comment by DukeVen** [comment]
![image](https://user-images.githubusercontent.com/64648810/137578330-f4dad6dc-9652-439d-bfcb-1033ffd013b2.png)

**Comment by DukeVen** [comment]
> Please share the node editor view (shading tab) with one of the objects selected.

![image](https://user-images.githubusercontent.com/64648810/137578340-b22beda0-d4bd-406e-9992-8565418cedc8.png)

**Comment by Parik27** [comment]
Thanks for reporting it :+1: 

I hadn't tested it with images without an alpha channel.
