### ISSUE TITLE
Import/export does not support vertex paint.

### ISSUE THREAD

**Issue by Allerek** [Parik27/DragonFF#116]
Hi, importing/exporting an object does no support vertex paint, in effect - if you import GTA:SA object, and export it - it will be bright as fuck.

**Comment by Calvin-rgb** [comment]
I have not met such a problem, the addon works well with the colors of the vertices of the object

**Comment by 669344682** [comment]
My vertex color works well.

**Comment by Calvin-rgb** [comment]
You needed to provide evidence that it is not working for you, and not rush to blame the problem.

**Comment by Allerek** [comment]
Blender 2.93.3

**Comment by Parik27** [comment]
You're wrong in your assumption that bright means the add-on doesn't support vertex paint (it does).

In your example if you change the vertex colours to be red you'll see the change in-game.
