### ISSUE TITLE
[Bug] The problem of exporting normals on vehicle materials

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#118]
There is a BMW e39 model, the model is displayed normally. I decided to change the model, imported the model into the editor, exported it to the game after the changes and saw a strange display of the door panes:
![](https://imgur.com/qqnrlXF.png)

And after importing this model back, I decided to make sure the grid was correct:
![](https://imgur.com/hqbgs6c.png)

This is how the glass looks before importing the model into the blender:
![](https://imgur.com/lhUoK0i.png)

I understand that the problem is in the addon, since there were no such problems before importing the model.

**Comment by Calvin-rgb** [comment]
I also tested the model with the Read material split flag, the problem remained

**Comment by Calvin-rgb** [comment]
I found a solution to this problem, as I found out the problem is in the wrong normals of polygons. You need to select the inverted polygons, make a flip, after which strange shadows will appear on the grid, then make a Set From Faces.
But the question still remains open, can you fix it?
![изображение](https://user-images.githubusercontent.com/52075975/140575895-d4f5d39d-d7c9-41d3-8546-120e0c151418.png)

**Comment by Calvin-rgb** [comment]
I thought that this problem concerns only one model, but for the experiment I opened another model of the Nissan S15, and I again saw the inverted normals of polygons on the glass material:
![изображение](https://user-images.githubusercontent.com/52075975/140579844-0c2bb5c4-38da-4b27-b8e7-cfa003be291f.png)

By the way: the texture superimposed on the material on these two models is absolutely the same, the texture is a resolution of 1x1 pixels. Drenched in black. BUT I think that this is not a problem because of the material that is superimposed on the mesh, but still the addon cannot correctly read the normals of polygons?

**Comment by Parik27** [comment]
Could you send me a model that has this issue so I could test it?

**Comment by Calvin-rgb** [comment]
Of course, I attached two archives at the bottom:
1. **s15_no_bug** - the original model, which was not changed with the help of DragonFF
2. **s15_bug_normals** - the model after exporting via DragonFF

_Note: in order to better see the inverted normals, it is better not to unpack the archive with textures._
[s15_bug_normals.zip](https://github.com/Parik27/DragonFF/files/7490041/s15_bug_normals.zip)
[s15_no_bug.zip](https://github.com/Parik27/DragonFF/files/7490046/s15_no_bug.zip)

@Parik27

**Comment by Calvin-rgb** [comment]
Can I also add some kind of notification when the model is successfully exported? It's just that my program freezes and I'm waiting for it to stop freezing, and even when it stops freezing, I don't see any notifications about the successful export of the model and I can continue to sit and wait like this🤦‍♂️

**Comment by Parik27** [comment]
CC @Calvin-rgb @ThePortuguesePlayer 

If you could check the next version in development here it'd be very helpful: https://github.com/Parik27/DragonFF/tree/new-export

I've changed the way the exporter generates the vertices/normals/etc., and it intends to fix custom normal and other geometry related issues. If you could check if the add-on produces correct results for models now, it'd be very helpful. 

I tested it with a cube, the results seem pretty promising, however we still need to make sure that anything else hasn't broken and large models export properly.

Comparison: (Left is exported with previous version, right is exported with the latest one on the new-export branch)
<img src="https://media.discordapp.net/attachments/682894128530456587/921673950193405962/unknown.png">

I also have pushed a fix for the SAMP 0.3.DL issue with skins getting deleted.

**Comment by Calvin-rgb** [comment]
I apologize for my long disappearance, I checked this branch of the add-on with that car model for GTA SA. And yet it seems to me that this problem lies precisely in this model, and not because of the script.
Perhaps this bug occurred when exporting this machine model to 3ds max.

**Comment by Calvin-rgb** [comment]
But the work with the export was done well, why can't it be introduced into the standard development branch? @Parik27

**Comment by Parik27** [comment]
I can merge it in the main branch, but it is about twice as slow as the previous method to export a model so I wasn't sure.

**Comment by Calvin-rgb** [comment]
Yes, I think it won't matter how long it takes to export
