### ISSUE TITLE
Question: how do I prepare model for export?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#121]
I want to export a vehicle model to SA, but I am unsure of how to set it up so it can be exported correctly.

**Comment by Skyliner77** [comment]
Just a world model or like a vehicle? First of all make sure you applied all transforms like scaling, rotating etc. you can do this by using cntr+A shortcut, then select rotation\scale, do not apply "location" it's used in very specific situations. Then make sure yours's model origins stays at 0.0.0 coordinates, you can do that by pressing Shift + S, selecting Cursor to world origin and then pressing RMB on your model, choosing "Set origin" -> "Origin to 3D cursor".
Make sure your normals facing right way, and your model has clean topology (no overlapping faces, double vertices and so on)
