### ISSUE TITLE
[Update Required] Loading Bones in Blender 3.0

### ISSUE THREAD

**Issue by GangstaRas** [Parik27/DragonFF#125]
I noticed that Blender 3.0 broke how bones are loaded. In Blender 3.0, it doesn't load the hierarchy properly, stopping at the "Root" parent.

For the Vertex groups associated, it picks up that they exist but it does not pick up their names, so it just says "Group.001" etc. going down.

This was tested on GTA SA and GTA VC PC DFF models if that helps

**Comment by Parik27** [comment]
Thanks for reporting that, I'll look into it.

**Comment by Parik27** [comment]
Should be fixed in 33ff7ef922b51a89b4486eb0f7cf1a246e894d6a. Re-open if there are any other issues.
