### ISSUE TITLE
Some models on import have strange shading

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#126]
Some modded vehicles when imported have strange shading when imported.
![image](https://user-images.githubusercontent.com/54049600/147842813-811877e8-1796-4ba3-8cb6-e01b4aff1501.png)
Vehicle used: https://gamemodding.com/en/gta-san-andreas/cars/70425-chevrolet-stepvan-30-1985.html

It can get fixed (albeit it still looks a little weird) by going into edit mode, selecting all the edges, and clicking on Mesh > Shading > Smooth Edges.
![image](https://user-images.githubusercontent.com/54049600/147842834-0de09288-31d8-4969-bf25-841d035575c9.png)

**Comment by Parik27** [comment]
I checked the model and the dff seems to have bad normals in the geometry (problem seems to be with the exporter that exported the dff).

 You can reset the custom normals using this button in the mesh properties:
<img src="https://media.discordapp.net/attachments/682894128530456587/926691103049125908/unknown.png">

I can add an option to skip importing custom normals in the future.

**Comment by umustbeloggedintododat** [comment]
It works, but when I press the button the model looks jagged. And if I try to export it Blender freezes.

**Comment by umustbeloggedintododat** [comment]
Ah, Blender was freezing because it was loading exporting. And I managed to make the model not look jagged/flat. Go To Mesh > Shading > Smooth Vertices.
