### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#127]
When importing this model: https://www.gtainside.com/en/sanandreas/cars/173723-ford-bronco-1975/
causes this issue:: List index out of range.

![image](https://user-images.githubusercontent.com/54049600/147852976-e8fd01ab-ab96-4727-9ad6-b144b32d44c8.png)

**Comment by umustbeloggedintododat** [comment]
It might either be the model locked or the size of DFF too big, the former would be a shame really, as the model looks so nice.

**Comment by Parik27** [comment]
The DFF is locked, yes.

**Comment by BAP00tato** [comment]
How do I unlock a renderware dff file?

I tried everything but no luck.

Btw this is a non GTA dff file!

Only the mesh imports but there's no bones in the armature!

**Comment by BAP00tato** [comment]
> How do I unlock a renderware dff file?
> 
> I tried everything but no luck.
> 
> Btw this is a non GTA dff file!
> 
> Only the mesh imports but there's no bones in the armature!

Update, I used renderware analyzer and there seems to be no lock.
