### ISSUE TITLE
Problem DFF import. One texture for the whole model

### ISSUE THREAD

**Issue by leminial** [Parik27/DragonFF#128]
![image](https://user-images.githubusercontent.com/83541050/147875430-2728a9ef-07d6-46e3-bd9b-4da33fb16568.png)
![image](https://user-images.githubusercontent.com/83541050/147875449-eef9ea3d-7277-4424-8530-5f2c03472a88.png)
При импорте модели в Blender, одна текстура накладывается на всю модель, как это можно исправить.
---
When importing a model into Blender, one texture is applied to the entire model, how can this be fixed.

**Comment by leminial** [comment]
![image](https://user-images.githubusercontent.com/83541050/147875516-c1fc5072-25a8-4a2c-8844-e9759c463f7b.png)

**Comment by Parik27** [comment]
This is a bug with models exported with KAMS, the materials aren't set properly in the geometry. You won't ever see this in normal models.

You have to check "Read Material Split" for it to import properly. It is not enabled by default because it causes issues importing non-SA models.

**Comment by vollkorn2** [comment]
Thanks a Lot for this Parik, 
I have the same Issue with GTA III Frosted Winter and GTA III Upstate Country Mod! 
Is it possible for you to provide this option for the Map Importer too? Or is it possible to change that easily for myself with Text Editer?

**Comment by vollkorn2** [comment]
@Parik27 
Did you read my message above?

**Comment by Parik27** [comment]
Sorry, must have missed it. I don't plan on making it on by default, but you can turn it on by changing this line in ops/map_importer.py
https://github.com/Parik27/DragonFF/blob/33ff7ef922b51a89b4486eb0f7cf1a246e894d6a/ops/map_importer.py#L107
to
```py
'use_mat_split'  : True,
```

**Comment by spicybung** [comment]
> This is a bug with models exported with KAMS, the materials aren't set properly in the geometry. You won't ever see this in normal models.
> 
> You have to check "Read Material Split" for it to import properly. It is not enabled by default because it causes issues importing non-SA models.

Late to the party, but this information is helpful. Exporting a model through 3DS Max that was affected by this issue, and then re-importing it to Blender, with "Read Material Split" on seems to have done the trick.
