### ISSUE TITLE
Some maps not import

### ISSUE THREAD

**Issue by BlenderBoyz** [Parik27/DragonFF#130]
Hi parik. Somw maps like interiors dont import. Can u fixed it or update the script? I will be happy

**Comment by ThePortuguesePlayer** [comment]
On that line, I've also observed that the COL importer doesn't import the Cube primitives, only the spheres and collision mesh.
Is that known?
Also, at export, the bounds are not calculated correctly (making the whole collision mesh shift away, not aligned with the DFF), but it can be corrected by opening the exported COL in COL Editor II and pressing Bounds > Optimum, and saving again. Whatever COL Editor does when you press that, it would be cool if the COL exporter also did.

**Comment by Parik27** [comment]
Map importer is experimental and only supports non-streamed ipl files, so you need to convert them to get them to import. 

@ThePortuguesePlayer Please create separate issue for that, it makes it easier to track that way.

**Comment by BlenderBoyz** [comment]
How? I searched some sites but i didnt get anything

**Comment by jgooderham** [comment]
My current pull request #316 addresses all these issues
