### ISSUE TITLE
Miscalculation of bounds in COL export

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [Parik27/DragonFF#131]
Original post from issue #130 :
"_On that line, I've also observed that the COL importer doesn't import the Cube primitives, only the spheres and collision mesh.
Is that known?
Also, at export, the bounds are not calculated correctly (making the whole collision mesh shift away, not aligned with the DFF), but it can be corrected by opening the exported COL in COL Editor II and pressing Bounds > Optimum, and saving again. Whatever COL Editor does when you press that, it would be cool if the COL exporter also did._"

Original collision model:
![image](https://user-images.githubusercontent.com/47691365/148684013-2779a75b-f96b-4e72-8790-ac77be422a6f.png)

Export from DragonFF:
![image](https://user-images.githubusercontent.com/47691365/148683851-f85ccdc2-c9fa-49c9-8619-cbc965effa0a.png)

After **Bounds > Optimum** in Collision File Editor II 0.4 Beta:
![image](https://user-images.githubusercontent.com/47691365/148683925-57f5b123-c715-4416-a3e1-ec08f3276712.png)

**Comment by jgooderham** [comment]
I've addressed this issue on my latest commit for #316
