### ISSUE TITLE
Facial Morph Support?

### ISSUE THREAD

**Issue by SonikkuA-DatH** [Parik27/DragonFF#133]
The GTA games don't use the DMA (delta morph animation) files, though many other Renderware games did. Someone did research on it a couple years ago (in the DeltaMorphPLGChunk class): 
https://github.com/DeadlyFugu/rwstreamlib/blob/master/src/geometry.cc
and in the DMorphAnimationChunk class:
https://github.com/DeadlyFugu/rwstreamlib/blob/master/src/animation.cc

**Comment by Parik27** [comment]
Someone seems to be working on it on a fork: https://github.com/Psycrow101/DragonFF/tree/delta_morph
