### ISSUE TITLE
Problem creating two layers

### ISSUE THREAD

**Issue by Nicolas3Ds** [Parik27/DragonFF#138]
I am creating a map file and in blender it is normal when I export it to the game it is missing a wall, there is only half of the wall and the other is missing

**Comment by Nicolas3Ds** [comment]
This error has been showing in the collision too, I went to see in another program how the collision was, it is inverted but it works, but the map is strange

**Comment by Parik27** [comment]
Seems like a backface culling issue to me:

1. You need to make sure that your wall has thickness (i.e it's not just a plane but a cube).
2. Make sure that the normals of your wall face in the right direction

**Comment by Parik27** [comment]
Not sure who you're referring to. If you want help with using Blender, this is not the right place to ask. 

<img src="https://media.discordapp.net/attachments/682894128530456587/948542773336899584/unknown.png"> This is what I mentioned in the first point. Your object should look like the one on the left and not the right.

**Comment by Nicolas3Ds** [comment]
I understand and there would be no way for me to leave the object the way it is on the right? to stay light

**Comment by Parik27** [comment]
You can disable backface culling (using whatever you are using to place the object in-game) if you are placing a map object, but otherwise not.

**Comment by Nicolas3Ds** [comment]
I found out that if I make a copy of the object and flip it with the mesh it makes the second wall, but the difference in lighting lol, now I don't know what to do

**Comment by Kiri678** [comment]
> I found out that if I make a copy of the object and flip it with the mesh it makes the second wall, but the difference in lighting lol, now I don't know what to do

Why not just recalculate outside faces trough alt+n menu, also difference in lighting might be said upside faces or vertex color
