### ISSUE TITLE
Export skin 

### ISSUE THREAD

**Issue by RACERNELEGALNY** [Parik27/DragonFF#149]
I import a standard skin, but if I export it and import it again, without editing, the vertex groups and bones break

It also prevents exporting a new skin

blender 3.1.2 , dragonff from from the "code" page
![image](https://user-images.githubusercontent.com/106018372/169695276-36b3681e-49af-4048-87a1-a974f8ebfe88.png)
![image](https://user-images.githubusercontent.com/106018372/169695426-f7f010c0-8595-4013-8353-6d20620de5fd.png)

**Comment by RACERNELEGALNY** [comment]
> Не удается воспроизвести проблему в последней версии Blender 3.1.2

Maybe there are suggestions what the problem might be? in some software?

**Comment by RACERNELEGALNY** [comment]
Сould it be affected by the fact that I was installing python on a PС?

**Comment by Parik27** [comment]
Also make sure you don't have the "Only Selected" option checked while exporting with only the mesh selected.
