### ISSUE TITLE
Import skin (Blender 3.1.2)

### ISSUE THREAD

**Issue by pureh14** [Parik27/DragonFF#150]
After importing a .dff file, I don't have a skeleton or bones at all (only root left).

ss:
![Screenshot 2022-05-23 214940](https://user-images.githubusercontent.com/106114366/169895277-e559bfc7-83a4-4a75-8a7b-c1d8fab2823f.png) 
ss2:
![Screenshot 2022-05-23 215019](https://user-images.githubusercontent.com/106114366/169895283-2b9be2d6-3716-419a-8472-8d730b513432.png)

**Comment by Parik27** [comment]
Share the dff file.

**Comment by pureh14** [comment]
[skin.zip](https://github.com/Parik27/DragonFF/files/8757859/skin.zip)

**Comment by Parik27** [comment]
Seems to load fine for me on the latest master branch:

<img src="https://media.discordapp.net/attachments/682894128530456587/978392997370658897/unknown.png">

**Comment by pureh14** [comment]
Something broke with an addon.

I **reinstalled** addon and it works well now. Thank you.

To anyone having this issue: It will be important to have "[the latest master branch](https://github.com/Parik27/DragonFF/archive/refs/heads/master.zip)".
