### ISSUE TITLE
Box collision 

### ISSUE THREAD

**Issue by RACERNELEGALNY** [Parik27/DragonFF#156]
-add box support when importing collisions
![image](https://user-images.githubusercontent.com/106018372/178010318-536d0d3d-6466-46f8-8397-3672103581e3.png)

**Comment by ThePortuguesePlayer** [comment]
I second this, as I reported this myself 7 months ago in issue #131.

**Comment by jgooderham** [comment]
Fwiw, I just implemented this in a commit for the current pull request I'm working on.
#316
