### ISSUE TITLE
SAMP 0.3Dl Custom skin Export problem

### ISSUE THREAD

**Issue by EvilsSoul** [Parik27/DragonFF#159]
[warning] Could not validate 0x7C57656B.dff. Error(44007:0x116) Deleting..

I'm trying to add a custom skin to my samp 0.3dl server, but I'm having this problem. How do I solve it?

(I unchecked the export collision and exported, and I tried all versions of 2.8x 2.9x, 3.0 and 3.2, but it didn't work.)

**Comment by Parik27** [comment]
Use the new-export branch from https://github.com/Parik27/DragonFF/tree/new-export
