### ISSUE TITLE
[Idea] Auto Alpha Connect for materials

### ISSUE THREAD

**Issue by Allerek** [Parik27/DragonFF#164]
Hi! I suggest adding auto Alpha Connect checkbox on import, for making renders etc. It should be a simple change in code that will save time for people that are doing renders.

**Comment by Parik27** [comment]
Not sure I get what you mean by Alpha Connect. If it's a simple change in code, you can likely do it yourself and make a pull request.

**Comment by Allerek** [comment]
> Not sure I get what you mean by Alpha Connect. If it's a simple change in code, you can likely do it yourself and make a pull request.

Im not really into python, but im sure its simple.
![image](https://user-images.githubusercontent.com/12304071/187222237-0a463796-3d1b-47fe-8dab-d16c0d3a6be4.png)
Its about connecting alpha from Image Texture to Principled BSDF to remove background from textures with transparency.

**Comment by Parik27** [comment]
That was added about a year ago 1d512166467e01132d98e1bccb92d6443a732d8b

**Comment by Allerek** [comment]
> That was added about a year ago [1d51216](https://github.com/Parik27/DragonFF/commit/1d512166467e01132d98e1bccb92d6443a732d8b)

using newest version of DragonFF on Blender 3.2.2, doesn't seem to work.

**Comment by Allerek** [comment]
> > That was added about a year ago [1d51216](https://github.com/Parik27/DragonFF/commit/1d512166467e01132d98e1bccb92d6443a732d8b)
> 
> using newest version of DragonFF on Blender 3.2.2, doesn't seem to work.

https://github.com/Parik27/DragonFF/blob/new-export/ops/importer_common.py#L91
this check might be a reason

**Comment by Allerek** [comment]
> > Just tested it and it does still work (I exported/imported a cube with a texture). The texture needs to have an alpha channel or it won't alpha connect (that's the purpose of the check).
> > Without the check, it produces undesirable results (see #113)
> 
> Im usually importing TGA textures with alpha and it doesn't seem to work for me.



> Just tested it and it does still work (I exported/imported a cube with a texture). The texture needs to have an alpha channel or it won't alpha connect (that's the purpose of the check).
> 
> Without the check, it produces undesirable results (see #113)

instead of providing 'color' node to 'alpha' just provide 'alpha' to 'alpha' :D

**Comment by Parik27** [comment]
What you're describing isn't trivial to do (the PrincipledBSDFWrapper does not provide any such methods as far as I'm aware). Again, I tested it with a tga file exported using GIMP, and it still 'alpha connects' as expected.

![image](https://user-images.githubusercontent.com/12731160/187456177-f386a1df-0d97-4cc2-8ce4-f5a214b1591e.png)

**Comment by Allerek** [comment]
> 
nope, its not connecting
https://streamable.com/wqc7fr

**Comment by Parik27** [comment]
The image files need to be in the same folder as the dff file for it to work otherwise the plugin can't open them to determine if they have an alpha channel.

**Comment by Parik27** [comment]
I implemented what you requested. Now the materials will always have alpha connected. Let me know if that fixes the issue.

**Comment by Allerek** [comment]
Yep, fixes entire problem. Thanks, appreciate that!
