### ISSUE TITLE
Unable to figure out problem when exporting a vehicle

### ISSUE THREAD

**Issue by PlatinMTA** [Parik27/DragonFF#166]
For some reason, the normals seem to export incorrectly. Tried with ``master`` and ``new-export``.

![image](https://user-images.githubusercontent.com/23291573/186446470-75ef849e-1ffe-4b3f-83b7-5859db75533c.png)
Auto-smooth is enabled

![image](https://user-images.githubusercontent.com/23291573/186446550-0f2c70d8-94ec-4137-8522-00069c9a3aa1.png)
In-game

![image](https://user-images.githubusercontent.com/23291573/186446723-d683d3a8-b101-4a5b-a966-90bdb3a0a5d3.png)
Original (wrong UV for the windows, and bad collisions, that's what I was trying to fix)

**Comment by ThePortuguesePlayer** [comment]
I had it happen too with two cars even with the new exporter.
One of the ways I solved it was to make sure the UVs were not separated islands at that place where the "mesh cracks".
The other way... I don't remember. I think I gave up and changed car.

**Comment by Parik27** [comment]
Original .dff and blend file would be very helpful in figuring out what causes it.

**Comment by PlatinMTA** [comment]
> Original .dff and blend file would be very helpful in figuring out what causes it.

[files.zip](https://github.com/Parik27/DragonFF/files/9420875/files.zip)

**Comment by Parik27** [comment]
I looked into it, and it seems like it's an issue with whatever exporter was used to initially create the dff file. I remember there being an issue with KAMS exported models having weird normals in the dff file. Basically when DragonFF re-exports it, it saves using those broken normals.

I'll be pushing an update that would add a checkbox to disable importing custom normals in dff files to address this issue.

**Comment by PlatinMTA** [comment]
Thank you Parik, I will look forward to that update. I will also, ofc, notify you if the problem has been solved.

**Comment by Parik27** [comment]
You can get it now, I pushed it in 1a5bfbf681ca02bc0988d0a3cc4a2b9ff463d753
