### ISSUE TITLE
GTA 3 Ped model import breaks the model

### ISSUE THREAD

**Issue by vakho10** [Parik27/DragonFF#168]
Hello there. I have a problem importing ped DFF into blender. The import outputs error messages about name and the model becomes broken. It has flipped parts. For example, the head is also where the leg is and so on. I will include the images below.
![2022-08-28_110442](https://user-images.githubusercontent.com/7012259/187061945-e6316f1d-e575-4097-b961-1295678f2303.png)
![2022-08-28_110459](https://user-images.githubusercontent.com/7012259/187061944-2dc6ddd7-b00b-4ffc-a9ee-63b694649544.png)
What should I do to fix this? :)

**Comment by DRAmazed** [comment]
Hi . Can U send the model file ? Maybe the script has a problem

**Comment by vakho10** [comment]
@DRAmazed Sure thing my man. Here you go: [prostitute.zip](https://github.com/Parik27/DragonFF/files/9459088/prostitute.zip)

**Comment by Parik27** [comment]
Use https://github.com/Parik27/DragonFF/tree/multi-clump

GTA 3 Ped and GTA SA Player Models use multiple clumps which aren't supported by the script. I recently implemented this feature and currently needs testing.

**Comment by vakho10** [comment]
@Parik27 Thanks. I've tested the import. I'll tell if the export works as well.

**Comment by vakho10** [comment]
@Parik27 Export works well too :)
