### ISSUE TITLE
Export custom normals for morphs (fork related)

### ISSUE THREAD

**Issue by SonikkuA-DatH** [Parik27/DragonFF#169]
Fork can be found here: https://github.com/Psycrow101/DragonFF/tree/delta_morph

With Psychrows' fork that enables importing/exporting morphs, I noticed that exporting the model causes issues of
-faces being split at parts, increasing vertex count/order
-normals being split similarly

While for static or skinned models this shouldn't be too much of an issue, the changed vertex order causes many issues for morphs

Here's a test for primitives;
https://youtu.be/sY1qjLgJfv4

And for a more complex model, vertex count before/after (before is 398 vertices)

![unknown-373](https://user-images.githubusercontent.com/58025603/189222529-56eaec8f-de60-4d73-ad9b-56f6a68cbd41.png)
![unknown-357](https://user-images.githubusercontent.com/58025603/189222531-57bfc7e0-c257-438f-8c49-b10919d7e123.png)

I feel this issue is with the base exporter in the main branch

**Comment by Parik27** [comment]
I'm not familiar with how the fork handles morph exports, but splitting vertices is important because RenderWare handles properties like UV coordinates, vertex colours and normals per vertex rather than per loop like Blender does. So when two faces share the same vertex, there needs to be duplication of the vertex to make sure that those properties are retained.

**Comment by SonikkuA-DatH** [comment]
Hmm, I see. So then the morphs should have the vertex list created after splitting, not before

Not sure how normals will be resolved. I'll let Psy know

**Comment by ThePortuguesePlayer** [comment]
Unrelated, but, curiosity is killing me because of how useful it would be to me. 
Does anyone know how one could use these morths in MTA:SA (outside of shader approaches using baked maps)?

**Comment by SonikkuA-DatH** [comment]
Psycrow has resolved the issue, thanks for explaining it
