### ISSUE TITLE
Export problem

### ISSUE THREAD

**Issue by Fertzoy** [Parik27/DragonFF#173]
Hi, I have a problem, when exporting to DFF, the Blender stops responding, the model is not exported, I tried old versions of the program and script, it didn't help, I also reinstalled the operating system. What could be the problem?

This happens with any model, I tried to wait, nothing happened.
Previously, everything was exported in 10 seconds.
![_S893NMHtHKAUFaGaKVaSIeoQxdgL3wTvt2I7OPdT-WdU5k-hdOTo2rwn8DJ4BmqsS4KOwP52G94PYdB9TBhk115](https://user-images.githubusercontent.com/99133520/192577393-0413fe4f-2207-42b1-854f-28faf655e407.jpg)

**Comment by boludoz** [comment]
Same problem
![image](https://user-images.githubusercontent.com/11653030/192887472-40bd3f24-b467-48f8-be40-78c65ce72822.png)
The program was previously tested with a lighter file and it worked perfectly.

**Comment by Parik27** [comment]
Please try the new optimized-export branch and see if that fixes your issue.

 https://github.com/Parik27/DragonFF/tree/optimized-export

Let me know if there are any issues with the export so I can merge it into master.

**Comment by Fertzoy** [comment]
Hi, there are no problems with exporting anymore, I didn't notice any other bugs. I'll let you know if there are any problems. Thank you for the quick fix, we appreciate your work <З
