### ISSUE TITLE
Col files are upside down after exporting and named wrong

### ISSUE THREAD

**Issue by Tonie2** [Parik27/DragonFF#180]
As above and in terms of wrong names
 they take .dff from file name to colection name when exported witch dff
![obraz_2022-10-12_164705270](https://user-images.githubusercontent.com/103835748/195374847-877d8c39-ee18-4ed1-9ba5-3fae6391d52a.png)

**Comment by Parik27** [comment]
No idea what you mean by 'upside-down'.

Also yes, that's intentional. They take the name of the collection because you can have multiple spheres/meshes in the same collision model.

**Comment by ElWonder666** [comment]
You must flip the faces polygon with shortcut shift + N or just N, the face orientation must to be inverted in blender

**Comment by Tonie2** [comment]
> No idea what you mean by 'upside-down'.

I meant that faces of col are to inside of models not outside(what indeed doesn't change much)

> Also yes, that's intentional. They take the name of the collection because you can have multiple spheres/meshes in the same collision model.

I meant when you export col witch dff col gets name "objectname".dff but to work ingame it should be "objectname"_col(at least according to how rockstar was naming them vanila game and most mods have them named)
