### ISSUE TITLE
Animation file help

### ISSUE THREAD

**Issue by njikmf** [Parik27/DragonFF#182]
I want to import models from another game written in renderware.And this plugin works good for models, but I need the animation data, could you please support this? Or could you please guide me how to do this ?
I can provide data files if you need

**Comment by Parik27** [comment]
The animation data is likely stored outside the DFF file, so it would be specific to the game. Do mention the game so I could take a look, but it probably is beyond the scope of the add-on  as I do not intend to add support for external file formats (formats other than DFF/TXD) for games other than GTA.

**Comment by Psycrow101** [comment]
If in another game the file extension with animation is `.anm`, then you can try [this addon](https://github.com/Psycrow101/Blender-3D-RW-Anm-plugin).

**Comment by njikmf** [comment]
![Capture](https://user-images.githubusercontent.com/96371060/195555996-76191715-76a8-4f3c-a9a4-bae6d6d20576.PNG)

**Comment by Psycrow101** [comment]
Animations import fine, but armature modifier and vertex group names are only added to single mesh, not all. How about adding support for multiple skinned objects here?
https://github.com/Parik27/DragonFF/blob/master/ops/dff_importer.py#L507

**Comment by njikmf** [comment]
![Capture](https://user-images.githubusercontent.com/96371060/195594709-5e6e0e0e-7a8d-4f29-bd6a-d752b5469f24.PNG)

First, import the dff, then import the animation , the leg looks so weird .... ?

**Comment by njikmf** [comment]
Thank your all!

**Comment by njikmf** [comment]
@Psycrow101  
Hello ! Thank you very much for the modification you made for me last time.
I recently encountered a problem again about the model import. The reason is this, so far all the character models are ok, because all models have skin data, but the building models is different, only part of mesh has skin.  I have studied for a long time and still don't know how to modify the code.
Could you help me to take a look?   Thank you very much!

[Desktop.zip](https://github.com/Parik27/DragonFF/files/10049082/Desktop.zip)
