### ISSUE TITLE
Problem while exporting model (dff)

### ISSUE THREAD

**Issue by almvx** [Parik27/DragonFF#183]
I can't export the model, it says this on every blend file, I'm using windows 11 and blender 2.93 version.

![Screenshot 2022-10-14 202357](https://user-images.githubusercontent.com/109543498/195915816-4ffdac6e-d37a-425a-9f15-dba2856cf4a2.png)

**Comment by Parik27** [comment]
Should be fixed in the latest commit. Any reason you're using 2.93 instead of the latest version?

**Comment by almvx** [comment]
I use it for modeling, I learned on that version
