### ISSUE TITLE
The problem with rendering alpha textures in the game

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#192]
I edited the model, it draws everything correctly in the program, all the settings seem to be correct, for some reason it does not draw the interior of the car through the rear-view window in the game.
How to fix it?
![](https://imgur.com/CmOZZP7.png)
![](https://imgur.com/RlbmmAt.png)

In Blender:
![](https://imgur.com/t0pY3uN.png)

**Comment by Calvin-rgb** [comment]
*The hierarchy has not changed
*Such a bug appears when the player gets into the car

**Comment by Calvin-rgb** [comment]
At the same time, I just replaced one alpha texture with another alpha texture

**Comment by Parik27** [comment]
Check #171 

It's to do with the order of the models and materials. Make sure the windows are below the chassis in the model hierarchy.

**Comment by Calvin-rgb** [comment]
> Check #171
> 
> It's to do with the order of the models and materials. Make sure the windows are below the chassis in the model hierarchy.

Yes, thank you
But just like other people, names are very important for the script to work and renaming is not very easy
I hope this can be fixed by changing the addon :)

**Comment by Calvin-rgb** [comment]
@Parik27 Hello
I have studied this problem a bit, as I think it is very important for a modding tool.
I used **Zmodeler 2.2.6** to edit the car model, and found out that this program, when exporting a DFF car model, moves all alpha materials to the end of the list of the hierarchy of materials. That is, it does not matter how the objects are placed on the stage and in the hierarchy, but it is important in what order the alpha materials are displayed in the general dff hierarchy.  

Am I thinking right?

If it still works, it would be possible to add this to DragonFF by adding a couple of parameters when exporting the model to the game. I would like to see a solution to this problem in the near future :)

**Comment by Parik27** [comment]
@Calvin-rgb I don't think it does that. The order of the objects does matter from my testing (read my comments on #171 ). Making the plugin reposition alpha materials on export breaks alpha properties of other objects (I tried by exporting a default GTA model). It also did not fix the issue in #171 which requires repositioning the objects. 

The material list is per-object, so even if you moved all alpha material to the bottom of the list, it won't fix the issue if the window model is placed above the chassis.

So to conclude, you can only see vertices through a transparent material:
- That are placed above the transparent object in the scene hierarchy
- (in case of the same object), vertices that have a material index higher than the transparent material (in Blender, you can reposition these slots in the material list).

It's not ideal to move all alpha materials to the bottom of the list (even if I add a checkbox, you might have a situation where you would want to have an alpha material placed above non-alpha materials). A more complex solution is required for this issue.

**Comment by Calvin-rgb** [comment]
@Parik27 I apologize for my wrong thoughts. 
I hope there is a solution to the problem, we will wait.

**Comment by Calvin-rgb** [comment]
UPD: Strangely, according to the hierarchy, I separated the glass from the back door, and this happened. Although the hierarchy of the interior of the car is higher in the hierarchy. I do not know what this is related to
![](https://imgur.com/JYWzpQN.png)

**Comment by Calvin-rgb** [comment]
There were problems with Z culling of the glass doors, I fixed it. Now I can't fix the interior display through the sunroof
I duplicated the hatch object, renamed it "zzz" and deleted its original. According to the hierarchy, it is below the model of the car interior, so what is the problem? @Parik27 
![](https://imgur.com/7DWjieS.png)

**Comment by Calvin-rgb** [comment]
Maybe try to implement flags for materials?
As it is done in zmodeler, by type _glass_mat [flag 4, spec]_

**Comment by Calvin-rgb** [comment]
> I would need the dff file for investigating it.
> 
> Is that functionality not available in the DragonFF Materials menu?
Here is the model
[car_bug.zip](https://github.com/Parik27/DragonFF/files/9899738/car_bug.zip)

----
I was thinking, and I thought maybe this is due to the fact that I set the "Read Material Split" parameter when importing the native model? And because of this, the ID of materials does not work correctly

**Comment by ThePortuguesePlayer** [comment]
For me, cars don't even import correctly without "Read Material Split" checked. They import with the materials assigned wrong.

**Comment by Calvin-rgb** [comment]
> For me, cars don't even import correctly without "Read Material Split" checked. They import with the materials assigned wrong.

My imports are fine, even with the Read Material Split turned off

**Comment by Calvin-rgb** [comment]
@Parik27 Good evening, I wanted to ask if you can share a script that can show the ID of the material in Blender.
The fact is that I somehow inexplicably solved the problem with the materials, and they began to show all the objects in the hierarchy. It was difficult, now I am very interested to look at it.

**Comment by Dotterkletch** [comment]
this occurs when the glass, and the surrounding model that you want to be visible through the glass, are connected. select the object that has the glass, go into edit mode, and select the faces that are going to have transparency, and press Y, this will detach it from the chasis, without separating it from its object. export it and check the results. I'm guessing this happens because just importing the model will merge the nearby vertices
