### ISSUE TITLE
Restriction of vertices to export DFF

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#194]
Is there any way to solve this problem?
![](https://imgur.com/npW3OxI.png)

The model is from another game, and you need to insert it into the MTA:San Andreas, I don't really want to download 3ds max

Can I add a parameter in the addon settings with setting vertex limits?

**Comment by Parik27** [comment]
It's impossible to export more than 65535 vertices in a single mesh. You can't simply remove the vertex limit. It won't be possible with 3ds max either.

**Comment by Calvin-rgb** [comment]
It's strange, but it's in a dff file of 125k vertices
I am exporting an already imported dff

**Comment by Parik27** [comment]
Can you send me the dff file? You can also uncheck 'Use Edge Split' while importing and try exporting it again.

**Comment by Calvin-rgb** [comment]
@Parik27 
[m8.zip](https://github.com/Parik27/DragonFF/files/9920735/m8.zip)

**Comment by Parik27** [comment]
Model imports and exports as-is just fine for me

**Comment by Calvin-rgb** [comment]
Is it imported without the Mass Export parameter?
