### ISSUE TITLE
Incorrect display of car interior elements

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#195]
At different camera angles, an element of the interior of the car disappears / appears
![](https://imgur.com/WofIk2g.png)
![](https://imgur.com/MhiXzfY.png)
What could have caused this to happen?
A collision or an incorrect hierarchy?

**Comment by Parik27** [comment]
Would be helpful to others if you mention what fixed it.

**Comment by Calvin-rgb** [comment]
I still didn't quite understand what
it was, but this bug is also present in standard GTA sa models, most likely these are problems of the game engine
