### ISSUE TITLE
col problem

### ISSUE THREAD

**Issue by 669344682** [Parik27/DragonFF#196]
![image](https://user-images.githubusercontent.com/7806033/200216667-1a2b9870-e9e9-43fc-8d9e-f848e613ff96.png)
![image](https://user-images.githubusercontent.com/7806033/200216749-5aab263a-f5c3-4931-9c21-1f3cc07061a5.png)
Why do I alway get this size of file? And wall seems like that boundary is not correct. Is that my mistake or something?

**Comment by 669344682** [comment]
660 byte

**Comment by 669344682** [comment]
![image](https://user-images.githubusercontent.com/7806033/200221758-170bb2b7-e610-4038-aa29-5e1bb9334092.png)
I have applied all changes

**Comment by ThePortuguesePlayer** [comment]
Have a read at issue #131 and see if it helps your case.
