### ISSUE TITLE
Exporting file error

### ISSUE THREAD

**Issue by Tervel1337** [Parik27/DragonFF#199]
Every time I try exporting a file, no matter if I've simply loaded a model or if I've modified it, I get this.
![image](https://user-images.githubusercontent.com/78919226/201212379-1d5d823d-abf4-4e7d-ba84-164d6bcc5002.png)

**Comment by Parik27** [comment]
Try using the typing branch (https://github.com/Parik27/DragonFF/tree/typing)

**Comment by Tervel1337** [comment]
> Try using the typing branch (https://github.com/Parik27/DragonFF/tree/typing)

Worked like a charm! Thanks.
