### ISSUE TITLE
Imported DFF has no armature

### ISSUE THREAD

**Issue by S00pergang** [Parik27/DragonFF#202]
### So I get an error when importing

> Python: Traceback (most recent call last):
>   File "C:\Users\⬛⬛⬛⬛\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\gui\dff_ot.py", line 268, in execute
>     importer = dff_importer.import_dff(
>   File "C:\Users\⬛⬛⬛⬛\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 822, in import_dff
>     dff_importer.import_dff(options['file_name'])
>   File "C:\Users\⬛⬛⬛⬛\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 794, in import_dff
>     self.import_frames()
>   File "C:\Users\⬛⬛⬛⬛\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\DragonFF-master\ops\dff_importer.py", line 713, in import_frames
>     obj.parent = self.objects[frame.parent]
> IndexError: list index out of range

### The model imports like this

![image](https://user-images.githubusercontent.com/112852330/210679578-2a42542e-66fb-44d2-a67e-53dc8d68ea4f.png)
_(Note: I can fix the missing textures and rotation easily)_

### And there seems to be a completely blank armature
![image](https://user-images.githubusercontent.com/112852330/210679952-a93f107e-0984-4e88-96d3-16b4be0dcdb9.png)

**This is a non GTA dff file, as this is from BBC Multimedia's Little Robots - Making Friends.**

**Comment by Parik27** [comment]
You will need to share your DFF file for me to debug it.

**Comment by BAP00tato** [comment]
https://www.mediafire.com/file/h3aahcow0xz0pwl/Rusty.dff/file
