### ISSUE TITLE
blender 2.79

### ISSUE THREAD

**Issue by uosofkho** [Parik27/DragonFF#204]
![Screenshot (154)](https://user-images.githubusercontent.com/84450206/212539391-8664d43c-b663-4285-bb01-c5c4cf0f53cd.png)
bug

**Comment by Parik27** [comment]
Not a bug

**Comment by uosofkho** [comment]
hello im cant endable on blender 2.79

**Comment by uosofkho** [comment]
@Parik27

**Comment by Parik27** [comment]
2.79 is not supported by DragonFF. Update to the latest version of Blender.
