### ISSUE TITLE
Blender col problem

### ISSUE THREAD

**Issue by LAASE** [Parik27/DragonFF#207]
So my plan was to make thing and export it to samp. The only problem is the col file. Im new to this and i hope you can help me with that. I create a brand new cube,resize it,also used loop cut and extrude to make a simple table.I select the object export it as .col and import it to col editor II and i get. My only goal is to fix that,because im new i dont know what the problem is and how to fix it.I would appreciate it if somebody can give me step by step instruction how to fix it,without that i cant continue my work.
![problem1](https://user-images.githubusercontent.com/72805613/217962674-b17f455b-1509-4b12-bd1e-7f0dfb1bbf7f.png)
![problem0](https://user-images.githubusercontent.com/72805613/217962687-d50c8998-b4b9-4d76-860b-ac45918b0c52.png)

**Comment by ThePortuguesePlayer** [comment]
Select your object in Blender (in Object mode), open the panel with the N key and check the Scale in Item tab.
![image](https://user-images.githubusercontent.com/47691365/217967720-a9a9b5a5-34a5-4324-ab5a-131bbf54c4f0.png)
If there's any other number there other than 1.0, on the 3D viewport and with your object selected, press Ctrl+A and apply transformations on Scale, then, reattempt the export.
Confirm later if it was that or not.
Also, it might help to refer to #131 .

**Comment by LAASE** [comment]
> Select your object in Blender (in Object mode), open the panel with the N key and check the Scale in Item tab. ![image](https://user-images.githubusercontent.com/47691365/217967720-a9a9b5a5-34a5-4324-ab5a-131bbf54c4f0.png) If there's any other number there other than 1.0, on the 3D viewport and with your object selected, press Ctrl+A and apply transformations on Scale, then, reattempt the export. Confirm later if it was that or not. Also, it might help to refer to #131 .

Thank you so much for you help. Now its working and the .col file is fine.Also i hope in the future this will work for anything.

**Comment by LAASE** [comment]
Now the problem is about the light.When i export the object and when i jump on it my character go dark like its night time.Is that a problem with vertex or something else? How to make it that its the same in day and night?

P.S In the night when character jump on the table he also turn black but its hard to see here on the picture.


![sa-mp-148](https://user-images.githubusercontent.com/72805613/218059443-d948764f-da3c-4ae1-a14a-1457d266a53f.png)
![sa-mp-149](https://user-images.githubusercontent.com/72805613/218059533-09f9de65-909e-4c20-8996-e0bb1b664cdd.png)
![sa-mp-150](https://user-images.githubusercontent.com/72805613/218059750-b6b405e9-2324-44be-b4e4-e23525e70299.png)
![sa-mp-151](https://user-images.githubusercontent.com/72805613/218059804-557f9e14-5e84-4b3b-9542-1b4205d5481e.png)

**Comment by Skyliner77** [comment]
https://imgur.com/a/6VE0Xj9
Add vertex colors, first Col responds for the day lighting, second for the night, simply google how to add vertex colors in blender, there are many tutorials on YouTube, and make sure that exporting options same as shown on screenshots.
P. S. I'll give more detailed explanation when I'll be back at home, feel free to ask any questions.

**Comment by LAASE** [comment]
> https://imgur.com/a/6VE0Xj9 Add vertex colors, first Col responds for the day lighting, second for the night, simply google how to add vertex colors in blender, there are many tutorials on YouTube, and make sure that exporting options same as shown on screenshots. P. S. I'll give more detailed explanation when I'll be back at home, feel free to ask any questions. P. P. S. There is dedicated wiki for this addon, https://github.com/Parik27/DragonFF/wiki/Creating-vertex-color-groups for some reason it didn't work for me at first, maybe I messed up exporting settings or something, I don't quite remember.

Thanks for you help, i managed to understand that vertex colors i think but still have problem with something else. The problem is about the character in the previous images.When i jump on the table my character change color as you can see.My goal now is that my character dont change color after jumping on the table like on the first image.

**Comment by LAASE** [comment]
I fixed the character lighting. You must edit the light in the Collision editor II. After that when you export the col and combined with the dff file it will work. Thanks you @ThePortuguesePlayer & @Skyliner77 for you help. You saved me lot of search time.
