### ISSUE TITLE
UV's are messed up.

### ISSUE THREAD

**Issue by Touhous4Life** [Parik27/DragonFF#217]
Whenever i import something like a car, UV's get messed up and look weird.

New Blender version on 3.50

**Comment by Calvin-rgb** [comment]
Screen?

**Comment by I3D99** [comment]
https://i.imgur.com/TmxeFqe.png

The UV map names are also appearing as "Float2" instead of "UVMap" as in previous versions of Blender

**Comment by Calvin-rgb** [comment]
Use version 3.4, these problems were not observed there

**Comment by Parik27** [comment]
This is a Blender bug:

https://projects.blender.org/blender/blender/issues/106430

Wait for the next Blender release.
