### ISSUE TITLE
Improve compatibility with Mashed models

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [Parik27/DragonFF#219]
[Bullet.zip](https://github.com/Parik27/DragonFF/files/11170647/Bullet.zip)
[City.zip](https://github.com/Parik27/DragonFF/files/11170704/City.zip)

Mashed is a racing game also using the RenderWare game engine, and as such, it uses DFF and TXD files for its models and textures.
DragonFF opens these with success, if all you want is models, however, no model is named in the outliner (I don't know if they are named to begin with), the rotation is wrong because these cars were saved with Y axis as up, and I _suspect_ there's some kind of shape key type of interpolation that is being discarded or just not imported right (for the driver's steering movements). I also believe the exported models will not work ingame, however, this is not a game I'm interested in modding at the moment, I just find it something interesting to look into in a not urgent manner.
I left exports of a car and a track on this post for people to experiment with.
I believe "not much work" is needed to get 100% compatibility with this game because of how close it is already.

**Comment by Psycrow101** [comment]
You can import these models in the latest version
