### ISSUE TITLE
The game crashes after exporting

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#220]
I export the minibus model, load it into the game and it crushes, and DffView shows it:
![](https://imgur.com/PClGRD0.png)

**Blender 3.4**
File:

[Stock.zip](https://github.com/Parik27/DragonFF/files/11180732/Stock.zip)

**Comment by LonelyMusicDisc** [comment]
How did you fix it?

**Comment by Calvin-rgb** [comment]
@LonelyMusicDisc 
No way.
I downloaded this model from an Internet source and it turned out to be already broken.
