### ISSUE TITLE
Feature: Allow Exporting without Bone Names / Frames

### ISSUE THREAD

**Issue by dreamsyntax** [Parik27/DragonFF#227]
Target Game: GUPE8P / Shadow The Hedgehog
RW Version: 3.7.0.2

Currently exporting will always result in frames being added. These frames contain the bone names.
I can safely delete them as the game does not expect them in RWAnalyze. However it would be more convenient to have an option to not export these as a checkbox in Export DFF.

![image](https://user-images.githubusercontent.com/14857235/231547389-3fef5175-768b-47f1-bf8f-8a5fc207b94b.png)

I plan to open a PR if I solve this.

**Comment by Psycrow101** [comment]
Is it enough to disable this operation?
https://github.com/Parik27/DragonFF/blob/master/ops/dff_exporter.py#L305

Something like this:
```python
if self.export_frame_nemes:
    frame.name = clear_extension(obj.name)
```

**Comment by dreamsyntax** [comment]
Closing as this #228 was merged
