### ISSUE TITLE
UV Anim keyframe interpolation

### ISSUE THREAD

**Issue by Dante-1337** [Parik27/DragonFF#229]
Hello, i been at it for a few hours now but i cant figure this out for the sake of me. Even tho i have the interpolation set to constant in blender (in order to jump from one frame to another), it still is linear in game, resulting in sliding thru the texture instead of jumping from one frame to the other. What am i missing?

_Originally posted by @Dante-1337 in https://github.com/Parik27/DragonFF/issues/59#issuecomment-1510606502_

**Comment by Psycrow101** [comment]
I think dff doesn't support constant interpolation, which is presented in Blender. You should set keyframes manually or use the bake action command.
