### ISSUE TITLE
DragonFF Export - Geo Byte Optimization / Export as Tri Strip Instead of Tri List?

### ISSUE THREAD

**Issue by dreamsyntax** [Parik27/DragonFF#231]
Left is original
![image](https://user-images.githubusercontent.com/14857235/236945797-a64ab7e1-e71c-44ec-af35-f74d45cb6218.png)
Right is export

116291 bytes (Original) vs 126629 bytes (DragonFF)
3DSMax RWIO plugin also produces similar 12XXXX byte result.

We found in Shadow the Hedgehog there exist a max number of polys/tris in an event scene at a given time.

Currently, RWIO or this plugin will export with a significantly bigger resulting DFF.

Using built in optimization tools in max/blender seems to destroy the proper skin in-games for whatever reason.

It was also noticed that DragonFF exports as Triangle List instead of Triangle Strip.

Is there any suggestion on potentially optimizing the output?
@Psycrow101 I used your multi mesh branch merged with the 'new-export' branch. Unfortunately same result, though I can confirm your atomic fix for multi mesh works.

**Comment by SonikkuA-DatH** [comment]
While this wouldn't affect GTA SA players too much for the PC port, console hacks may suffer from performance issues or harsher culling. In Shadow's case, harsh culling limits

**Comment by Psycrow101** [comment]
@dreamsyntax This PR should solve the issue
https://github.com/Parik27/DragonFF/pull/281

**Comment by dreamsyntax** [comment]
@Psycrow101 I'm not sure if I'm doing something wrong, is this not compatible with multi-mesh?
For Shadow use case it requires multi-mesh as event DFFs are usually multi mesh / multi atomic

I merged multi-mesh branch with your new PR as a test but no luck with the options
![image](https://github.com/Parik27/DragonFF/assets/14857235/490d3791-5408-4bf5-8030-f9024c3b4f84)
![image](https://github.com/Parik27/DragonFF/assets/14857235/43740ac6-a1ac-45c8-8543-aebe982bbc7e)


Source asset in question:
 
[EV_SHADOW_DFF.zip](https://github.com/Parik27/DragonFF/files/14397419/EV_SHADOW_DFF.zip)

**Comment by dreamsyntax** [comment]
Ok after selecting each mesh per your instruction, I can confirm it works as expected in-game as well!

old dff export (no tristrip, hitting the cull limit)
![image](https://github.com/Parik27/DragonFF/assets/14857235/121390f2-e527-43bb-8015-9049e39bf1b9)

new dff export (tristrip):
![image](https://github.com/Parik27/DragonFF/assets/14857235/278e761a-3c73-457a-b977-ff6d4384fb31)


```
original dff:
120kb

old dff export (no tristrip)
134kb

new dff export (tristrip):
123kb
```

The output size is still slightly larger than the original, but this is a HUGE improvement.

Thank you very much!

**Comment by dreamsyntax** [comment]
After doing some additional tests, some DFFs will result in larger file sizes than original, but are still less than pre-tristrip and pre-optimization. Notably EV!SIREIKAN2!LOCATOR.DFF from event1101_sceneA /  event1101_sceneB - and completely does not load (bad DFF format?) under any export configuration.

**Comment by dreamsyntax** [comment]
Adding this here for anyone else trying to take advantage of this feature.

Note: 
Blender used was 4.1.1
Last tested commit: 19f2d3f, June 22, 2024 12:12PMUTC
Used the multi-mesh variant from Psycrow101/DragonFF:multi-mesh
Though if your target model is non-multi mesh you can use the master branch from Parik27.

### Import Args for 1:1 with original game's model:
[x] Load TXD
[x] Skip mipmaps
[ ] Connect Bones
[x] Scan for Images
[ ] Read Material Split
[ ] Use Edge Split
[x] Import Custom Normals
[ ] Group Similar Materials

Once imported, you must click within each mesh (one at a time) like in this image:
![image](https://github.com/Parik27/DragonFF/assets/14857235/b2e44bf0-419d-423b-a4df-19e84728f12b)

Not all meshes may have everything checked. Some may have Modulate Material Color checked, while others don't for example. Leave those alone, you only want to adjust:

[x] Export Normals
[x] Export Custom Split Normals
[x] Use Triangle Strip

When Exporting, I have all exporter options unchecked. RW Version doesn't matter, but 3.7.0.2 is what Shadow used.
[ ] Mass Export
[ ] Only Selected
[ ] Export Collision
[ ] Export Frame Names
[ ] Exclude Geometry Faces

Lastly after exporting, you will need to use RWAnalyze 0.4 BETA and fix Right To Render having a wrong byte:
Navigate to any Atomics with "Right To Render", and hex edit or replace them with the original file. As of this commit, usually only one byte is incorrect, which results in wrong material rendering. 
ex:
WRONG:
```
16 01 00 00 01 00 00 00 
```
CORRECT:
```
16 01 00 00 02 00 00 00
```


----

Closing this issue as this feature has been extensively used. Thanks for all the hard work.
