### ISSUE TITLE
Texture does not load

### ISSUE THREAD

**Issue by Krithish079** [Parik27/DragonFF#232]
After I import the dff, the texture does not load while viewport shading is set to texture, 
![Screenshot (7)](https://github.com/Parik27/DragonFF/assets/118073742/20dd314a-dca8-4bf4-8652-fa54a0b570b2)

**Comment by clmjffr** [comment]
Have you extracted the textures from the TXD file as png/bmp/jpeg with a tool such as TXD Workshop ?

**Comment by Krithish079** [comment]
> Have you extracted the textures from the TXD file as png/bmp/jpeg with a tool such as TXD Workshop before importing the DFF in Blender ?

After i extract, how do i add the texture to the model?

**Comment by clmjffr** [comment]
When importing a dff model, the plugin will automatically look for an image file of the same name in the same folder if the "Scan for Images" checkbox is indeed checked. So you won't have to do anything else.

For instance, make sure that you have those two files in the same folder :
-ballas1.dff
-ballas1.png
And when importing make sure that "Scan for Images" is checked, and that the "Extension" dropdown is set on "PNG"

**Comment by Krithish079** [comment]
> When importing a dff model, the plugin will automatically look for an image file of the same name in the same folder if the "Scan for Images" checkbox is indeed checked. So you won't have to do anything else.
> 
> For instance, make sure that you have those two files in the same folder : -ballas1.dff -ballas1.png And when importing dff make sure that "Scan for Images" is checked, and that the "Extension" dropdown is set on "PNG"

That works, Thanks for helping

> > Have you extracted the textures from the TXD file as png/bmp/jpeg with a tool such as TXD Workshop before importing the DFF in Blender ?
> 
> After i extract, how do i add the texture to the model?

That works, Thanks!

**Comment by Krithish079** [comment]
> When importing a dff model, the plugin will automatically look for an image file of the same name in the same folder if the "Scan for Images" checkbox is indeed checked. So you won't have to do anything else.
> 
> For instance, make sure that you have those two files in the same folder : -ballas1.dff -ballas1.png And when importing dff make sure that "Scan for Images" is checked, and that the "Extension" dropdown is set on "PNG"

That works, Thanks!
