### ISSUE TITLE
Unpack_from requires a buffer of at least 2 bytes

### ISSUE THREAD

**Issue by ran-j** [Parik27/DragonFF#235]
![image](https://github.com/Parik27/DragonFF/assets/17410205/4bc37679-71e6-4b60-9a54-b0f67cecc28c)

I'm trying to load a model from a PS2 game called Shijyou Saikyou no Deshi Kenichi - Gekitou! Ragnarok Hachikengou.

But i'm geting this error.

Here is the source model: https://drive.google.com/drive/folders/13Wwkr_ceYsCrMtqopm13JRtIHihxwtw8?usp=sharing

**Comment by Psycrow101** [comment]
This dff contains a Native Data PLG section, which, unfortunately, is not yet supported
