### ISSUE TITLE
Duplicate and misnamed materials.

### ISSUE THREAD

**Issue by JohnnieBR1** [Parik27/DragonFF#238]
I have a problem with materials being duplicated for each part of a model on every import. For example, my car doors might use a common material, but that material is always duplicated for each one individually. Also, the names don't come wrong, and it would be nice to have the actual names of the materials instead of renaming them.

**Comment by Parik27** [comment]
There must be distinction between the materials or they would not be duplicated. The add-on tries to group materials (there's an import option). Moreover, grouping materials may cause issues with material order in DFF exporting in some cases so you might not want it anyway.

There are no names stored for materials in the DFF file, so it's impossible to have actual names of material.

**Comment by JohnnieBR1** [comment]
Oh right, thanks.
