### ISSUE TITLE
Texture not showing

### ISSUE THREAD

**Issue by Ghost6461** [Parik27/DragonFF#242]
Hello I've exported this character from gta sa but when I've imported it and changed to texture mod or material mod the texture not showing as shown .. any help please ?
**Note t
![IMG_20230826_195332](https://github.com/Parik27/DragonFF/assets/128511218/21849661-e8c3-4466-9772-413724654ca1)
hat my folder included everything ( ballas2.dff / ballas2.txd / ballas2.png )

**Comment by Parik27** [comment]
This seems to be Blender 2.7 which is not supported.

**Comment by Ghost6461** [comment]
> This seems to be Blender 2.7 which is not supported.

It's 2.79 yes .

It's not supported ?

**Comment by Parik27** [comment]
It is not supported. You need to use the latest version of Blender. You realize 2.79 is a 4 year old version, right?

**Comment by Ghost6461** [comment]
> It is not supported. You need to use the latest version of Blender. You realize 2.79 is a 6 year old version, right?

Ye .. but my pc is so bad ... It's impossible to do it on 2.79?

**Comment by Ghost6461** [comment]
> It is not supported. You need to use the latest version of Blender. You realize 2.79 is a 6 year old version, right?

I've also seen someone uses dragondff on blender 2.79 Soo ?

**Comment by Ghost6461** [comment]
> It is not supported. You need to use the latest version of Blender. You realize 2.79 is a 6 year old version, right?

Can you reply me please ?

**Comment by Parik27** [comment]
Sorry, like I said, use the latest version of Blender. This is not an issue.
