### ISSUE TITLE
Error Report When Importing Model From player.img

### ISSUE THREAD

**Issue by johnnie-br** [Parik27/DragonFF#244]
When importing a DFF from player.img, this occurs in the Blender Info Log:

```
Python: Traceback (most recent call last):
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\gui\dff_ot.py", line 268, in execute
    importer = dff_importer.import_dff(
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 824, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 796, in import_dff
    self.import_frames()
  File "C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\DragonFF-master\ops\dff_importer.py", line 675, in import_frames
    obj = bpy.data.objects.new(frame.name, mesh)
TypeError: BlendDataObjects.new(): error with argument 1, "name" -  Function.name doesn't support None from string types
```
Here are the files I intended to edit and they didn't work:
[vest.zip](https://github.com/Parik27/DragonFF/files/12592008/vest.zip)

**Comment by Parik27** [comment]
Use the multi-clump branch to import player models. 

https://github.com/Parik27/DragonFF/tree/multi-clump

**Comment by johnnie-br** [comment]
> Use the multi-clump branch to import player models.
> 
> https://github.com/Parik27/DragonFF/tree/multi-clump

Ok, tank you.

**Comment by johnnie-br** [comment]
![image](https://github.com/Parik27/DragonFF/assets/133685928/9d473c25-a60a-4708-ad40-deb0fa9afe54)
Why does this problem occur when importing a model that I exported? Basically lost the names of all vetex groups, meshes, shape keys changed to those of the original CJ model...
![image](https://github.com/Parik27/DragonFF/assets/133685928/abed7a89-9c8f-40be-a8d8-a608c01d5d4f)

**Comment by johnnie-br** [comment]
Here is my .blend file in case it might help you in any way.
[Jose.zip](https://github.com/Parik27/DragonFF/files/12605087/Jose.zip)

**Comment by johnnie-br** [comment]
@Parik27 Any news?

**Comment by NaufalFajri** [comment]
use this?
https://github.com/Parik27/DragonFF/tree/typing

**Comment by johnnie-br** [comment]
> usa isto? https://github.com/Parik27/DragonFF/tree/typing

What is this? @NaufalFajri

**Comment by NaufalFajri** [comment]
use typing branch to import player models

**Comment by johnnie-br** [comment]
Well, the problem has been resolved. Thank you to everyone who offered to help. The cause was the lack of painting influence on the bones of the player's body.

**Comment by johnnie-br** [comment]
Well, the problem has been resolved. Thank you to everyone who offered to help. The cause was the lack of painting influence on the bones of the player's body.
