### ISSUE TITLE
Morphs revert commit error

### ISSUE THREAD

**Issue by SonikkuA-DatH** [Parik27/DragonFF#246]
Around 2022 @Psycrow101 implemented Morph plg support for his fork of DragonFF. Early October 2022 you merged his difference
However after the 12th of Oct. this commit you did later seems to have accidentally disabled support https://github.com/Parik27/DragonFF/commit/b32230cd5f8599ef80a249f8e8eb29d9e366e7c2

Because of this, none of the delta morphs import. This also makes @Psycrow101 's DMA plugin unusable, as it relies on the morphs

**Comment by Parik27** [comment]
Can you share a DFF file with a delta morph for testing?

**Comment by SonikkuA-DatH** [comment]
Sure, here are some samples
[DFF with Morphs](https://drive.google.com/file/d/16KciLKaMWD153wqCjVqd9gqyg5ulAlYK/view?usp=drivesdk) 
If it works, it should be able to have the morphs in Blender's green triangle panel, with names of each morph noted

**Comment by Psycrow101** [comment]
Looks like the problem is an incorrect offset after reading the User Data PLG section.
PR with bug fix: https://github.com/Parik27/DragonFF/pull/251
