### ISSUE TITLE
New Script: TXD Name as Texture Prefix! (Like in Magic TXD)

### ISSUE THREAD

**Issue by vollkorn2** [Parik27/DragonFF#249]
Hello @Parik27, 
I didn't wrote anything new here for a long time. 

I've looked in the game files for the correct TXD Name for each Texture used in by the DFFs. 
They are all defined in the IDEs (in case somebody didn't know, just like me)
All missing definitions are in the generic IDE (SA: Folder "generic")

So my question: 
Is there a way to assign only correct Textures from the correct TXD to the Models? 
Like in Magic TXD you can extract with TXD Name (indust1_Alumox64b / joeys_Alumox64b / compark_Alumox64b)
compark_Alumox64b is different (Alpha Channel) and gets overwritten without TXD Name

Example SA: yellowscum64 / VC: metalcopy / III: Alumox64b

for GTA III i needed 6h to fix this by hand (Result is on YouTube by the way: [https://youtu.be/fBlKpHFB_nY] )

**Comment by vollkorn2** [comment]
For those who want to delete/replace all "Real" duplicated Textures: 

AllDup is a free software to find all Identical Images (you can export the Result as Text File!!!)
With Python I can write a Blender Script to Replace all Duplicated Textures with the first One. 
But before it must be possible for DragonFF to assign the TXD name correctly.

Also it would help a lot if the Material Name is identical with the TXD+TextureName by default, but i've already a script for this.

**Comment by vollkorn2** [comment]
If I'm right, all the missing Entrys are in Generic.IDE > so all DFFs should have there own TXD defined. 

Your Python scripts are still too complicated for me so I still need help on Implementing such a feature. 
I would do Changes like this: 

`CurrentDffName = DffName       # Save the DFF Name to Variable 
with open (generic.ide, r)              # and Imported IPL
        # save all Entrys to List 
        if CurrentDffName in List: 
                  TxdPrefix = Text[Line]  # Save TXD Name
    
NewTextureName = TxdPrefix+Texture
bpy.data.materials.new(name=NewTextureName)
bpy.data.images.load(NewTextureName)`

**Comment by Psycrow101** [comment]
Can you provide the necessary files for the test? Perhaps I can help with this.

**Comment by vollkorn2** [comment]
There's no need to provide Files 
I just use GTA III PC v.1.1 and extract the map.
For example in Indust_NE (Junkjard) the crane has wrong Textures (Only Alpha Channel Missing)

I already have written my own script to run afterwards, GTA III works perfect but VC and SA is not Testet yet (Frosted Winter and Stories Conversions should work too after Debugging) 

My script does the Following: 
Find and Read all IDEs in the given Filepath 
Save all DFFs and TXDs in two Lists 
Loop through all Collections (with Correct DFF name) 
Loop Through all Meshes (but no duplicates)
Loop Through all Material Slots 
Get Texture Name (Find DFF name in List) 
Get TXD name from List add to Texture Name 
Replace and Create New Material with new Texture 

Does work pretty well.

**Comment by vollkorn2** [comment]
My script is Finished and Testet on GTA III, GTA Frosted Winter and GTA VC (GTA SA is not testet because I always used GTA Tools for that).
Written as a single Script to run in Text Editor.
Use Original TXDs (with all Duplicates) or use AllDup to use only first Texture of the Duplicates.
[ReadMe_TxdNamePrefix.txt](https://github.com/Parik27/DragonFF/files/12806653/ReadMe_TxdNamePrefix.txt)
[TxdNameAsTexturePrefix.txt](https://github.com/Parik27/DragonFF/files/12806662/TxdNameAsTexturePrefix.txt)
The Second File has to be Renamed from .txt to .py
