### ISSUE TITLE
The skins exported with the addon are deformed when the mod "Mod Ragdoll Bullet Physics" is installed.

### ISSUE THREAD

**Issue by MrSopaipilla** [Parik27/DragonFF#252]
The skins that are exported with the add-on have a strange behavior when using the previously mentioned mod, they deform and break the proportions of the model, with skins made with other programs such as 3ds max this does not happen.

Mod:
[https://www.mixmods.com.br/2021/09/mod-ragdoll-bullet-physics-fix-fisica-realista/](url)

![image](https://github.com/Parik27/DragonFF/assets/65387124/b686ea1b-5aca-4135-b74d-c3660d252742)

**Comment by Psycrow101** [comment]
This change should fix your problem
https://github.com/Parik27/DragonFF/pull/254
