### ISSUE TITLE
Feature: Support for Embedded Mesh in Bone

### ISSUE THREAD

**Issue by dreamsyntax** [Parik27/DragonFF#253]
There exists some models in Shadow the Hedgehog and Sonic Heroes where meshes are attached to bone, and bones may be nested within those skins. OMEGA.DFF is one such model.

The model throws this error on import with DragonFF
![image](https://github.com/Parik27/DragonFF/assets/14857235/6dc74151-dee3-4716-9621-7a3989025d3f)
![image](https://github.com/Parik27/DragonFF/assets/14857235/5fc4bd00-d821-4288-a661-0cbd46db6d86)

The model throws this error on import with @Psycrow101 's DragonFF-multimesh
![image](https://github.com/Parik27/DragonFF/assets/14857235/8861c3a0-3969-43ab-897f-340e03bb0bd6)
![image](https://github.com/Parik27/DragonFF/assets/14857235/c9c43120-432e-45b8-a11f-563f8235536e)

![image](https://github.com/Parik27/DragonFF/assets/14857235/352c4c71-ee6c-4871-b0c9-382472833a93)

Source for debugging:
Shadow the Hedgehog Omega:
[omega.zip](https://github.com/Parik27/DragonFF/files/12838942/omega.zip)

3DSMax Hierarchy Example:
Where tri = bone; Circle = mesh
![unknown](https://github.com/Parik27/DragonFF/assets/14857235/ac1a5804-2e3e-4436-b948-98c63f171b6b)

![image](https://github.com/Parik27/DragonFF/assets/14857235/9d0baa69-b7d2-4221-b0e2-f8952090189a)

**Comment by RaphaelDrewBoltman** [comment]
following this issue and attaching Omega and Tails from Sonic Heroes, as those suffer from the same exact issue:
[OMEGA_TAILS-SH.zip](https://github.com/Parik27/DragonFF/files/12839016/OMEGA_TAILS-SH.zip)
this one including the model (DFF), textures (TXD and PNG) and animations (ANM) for more diversity on testing the models during and after the procedure.

**Comment by Psycrow101** [comment]
DragonFF uses data extracted from the skin section to create frames for the scene. In Omega, skin sections are missing, which is why the armature to which the meshes are attached is not created. This causes an exception to be thrown in the multi-mesh addon.

To fix this problem, we need to figure out how to combine skin data and frame data. I think we should create armature based on frame data, supplementing it with skin data, but I'm not sure that the frame transformation matrices will exactly match the skin transformation matrices. I'll try to experiment with this, but I can't guarantee perfect results.

For now I have coded a temporary fix for Omega.

![image](https://github.com/Parik27/DragonFF/assets/31922454/015c8aec-5115-4536-9f39-4026ab971992)

Please note that the armature will not be created, resulting in incorrect export and animations.

[DragonFF.zip](https://github.com/Parik27/DragonFF/files/12840476/DragonFF.zip)

**Comment by dreamsyntax** [comment]
> DragonFF uses data extracted from the skin section to create frames for the scene. As dreamsyntax said, in Omega, skin sections are missing, which is why the armature to which the meshes are attached is not created. This causes an exception to be thrown in the multi-mesh addon.
> 
> To fix this problem, we need to figure out how to combine skin data and frame data. I think we should create armature based on frame data, supplementing it with skin data, but I'm not sure that the frame transformation matrices will exactly match the skin transformation matrices. I'll try to experiment with this, but I can't guarantee perfect results.
> 
> For now I have coded a temporary fix for Omega.
> 
> ![image](https://user-images.githubusercontent.com/31922454/273443097-015c8aec-5115-4536-9f39-4026ab971992.png)
> 
> Please note that the armature will not be created, resulting in incorrect export and animations.
> 
> [DragonFF.zip](https://github.com/Parik27/DragonFF/files/12840476/DragonFF.zip)
> 
> UPD: with armature
> 
> [DragonFF.zip](https://github.com/Parik27/DragonFF/files/12840718/DragonFF.zip)

Unsurprisingly importing MTN files do not work properly, but with armature available its a step in the right direction! Thank you very much

**Comment by Psycrow101** [comment]
> Unsurprisingly importing MTN files do not work properly, but with armature available its a step in the right direction! Thank you very much

I checked omega.bon and found that some bone ids are unexpectedly undefined (have a value of -1). Try the modified version of io_scene_sth_mtn. Animations should work correctly.
[io_scene_sth_mtn.zip](https://github.com/Parik27/DragonFF/files/12850674/io_scene_sth_mtn.zip)

**Comment by dreamsyntax** [comment]
> > Unsurprisingly importing MTN files do not work properly, but with armature available its a step in the right direction! Thank you very much
> 
> I checked omega.bon and found that some bone ids are unexpectedly undefined (have a value of -1). Try the modified version of io_scene_sth_mtn. Animations should work correctly. [io_scene_sth_mtn.zip](https://github.com/Parik27/DragonFF/files/12850674/io_scene_sth_mtn.zip)

Ah I recall running into that while trying to update the 3dsmax bon script. Giving it a try

**Comment by dreamsyntax** [comment]
Seems good for the few I've tried!

https://github.com/Parik27/DragonFF/assets/14857235/69773b30-a136-421d-9d87-0a1a3ce7a9e7



https://github.com/Parik27/DragonFF/assets/14857235/9204ad20-ac55-4cb0-9d9a-400c000b0acb

I will verify the heroes models next, to see if they also work properly. Thank you!

This is a bit off topic, but I can't seem to trigger your bulk import function for .mtn.

I see the code change, but when selecting a folder no mtns are imported. When multi-selecting individual mtns it just defaults to the first letter one.

**Comment by dreamsyntax** [comment]
The two known problematic models in heroes work fine + tested the existing rw anm plugin.

https://github.com/Parik27/DragonFF/assets/14857235/91a238c8-6eff-4f91-bd9c-000c260b2c7c

https://github.com/Parik27/DragonFF/assets/14857235/d2449da0-c784-456d-8d28-f8b79ef41575

Seems good to me, I'll leave this open until the PR is created / merged.

**Comment by dreamsyntax** [comment]
This probably an issue for the sh mtn plugin, but figured its relevant here. While Omega is fixed, Shadow Tails is not. I think this is because of the multi .bon case

Image on TAILS.DFF -> TAILS.BON -> tails_atc.MTN
![image](https://github.com/Parik27/DragonFF/assets/14857235/c6930328-a978-4a6e-8c50-8c5b3d0a1791)

[TAILS_SHAD.zip](https://github.com/Parik27/DragonFF/files/12851039/TAILS_SHAD.zip)

**Comment by dreamsyntax** [comment]
Another such similar case of nested mesh is GUNBIGFOOT

With this DragonFF update the initial DFF works fine, but again MTN does not
![image](https://github.com/Parik27/DragonFF/assets/14857235/42f922ca-5622-42a4-941c-df4a505d90c3)


![image](https://github.com/Parik27/DragonFF/assets/14857235/67e4eb81-4801-4e3a-b8d9-ece2c633a9c7)


[SHADOW_BIGFOOT.zip](https://github.com/Parik27/DragonFF/files/12851080/SHADOW_BIGFOOT.zip)

**Comment by dreamsyntax** [comment]
> > Unsurprisingly importing MTN files do not work properly, but with armature available its a step in the right direction! Thank you very much
> 
> I checked omega.bon and found that some bone ids are unexpectedly undefined (have a value of -1). Try the modified version of io_scene_sth_mtn. Animations should work correctly. [io_scene_sth_mtn.zip](https://github.com/Parik27/DragonFF/files/12850674/io_scene_sth_mtn.zip)

Just an update on this, this seems to break for all other animations besides omega. Shadow's animations become scrambled if using this version.

**Comment by dreamsyntax** [comment]
> Or try this [DragonFF.zip](https://github.com/Parik27/DragonFF/files/12859470/DragonFF.zip)

BigFoot anims look mostly good, I noticed there's a few frames that seem to spasm out in most anms

BFA_WALK
https://github.com/Parik27/DragonFF/assets/14857235/eabb653a-3277-4a90-8e32-e5abac22f9e3

BFA_DAMAGE
https://github.com/Parik27/DragonFF/assets/14857235/37b73ea5-c55a-41d4-9e0c-960975af0c94

Tails seems to work properly now.
Shadow seems to work properly now.

> I see the code change, but when selecting a folder no mtns are imported. When multi-selecting individual mtns it just defaults to the first letter one.
I still can't figure out how to invoke your bulk import you added.

**Comment by Psycrow101** [comment]
> I still can't figure out how to invoke your bulk import you added.

In Blender, animations are available in the Dope Sheet editor (Shift + F12). There you need to go to Action Editor. A list of actions will be available on the right.
![image](https://github.com/Parik27/DragonFF/assets/31922454/180c2a88-c520-471a-8a5e-c185af7af545)

> BigFoot anims look mostly good, I noticed there's a few frames that seem to spasm out in most anms

The problem is with the io_scene_sth_mtn addon. Wrong Bezier curve handlers result in incorrect keyframe interpolation. I'll see what went wrong.

**Comment by dreamsyntax** [comment]
> Or try this [DragonFF.zip](https://github.com/Parik27/DragonFF/files/12859470/DragonFF.zip)

To re-iterate the status of this, which branch will this live in and does it make sense to have this as a PR for the main branch or only multi-mesh?

**Comment by Psycrow101** [comment]
> > Or try this [DragonFF.zip](https://github.com/Parik27/DragonFF/files/12859470/DragonFF.zip)
> 
> To re-iterate the status of this, which branch will this live in and does it make sense to have this as a PR for the main branch or only multi-mesh?

This change is currently in the multi-mesh branch. I think this branch is not tested enough to merge into the main branch.

**Comment by dreamsyntax** [comment]
> > > Or try this [DragonFF.zip](https://github.com/Parik27/DragonFF/files/12859470/DragonFF.zip)
> > 
> > 
> > To re-iterate the status of this, which branch will this live in and does it make sense to have this as a PR for the main branch or only multi-mesh?
> 
> This change is currently in the multi-mesh branch. I think this branch is not tested enough to merge into the main branch.

@Psycrow101 would be curious on your thoughts about a checkbox option in the DFF Import/Export popup.
Would it be unfeasible given the amount of changes? The dual branches leads to come confusion for end users.
