### ISSUE TITLE
Transparency issues with materials.

### ISSUE THREAD

**Issue by Amir1386kazemi** [Parik27/DragonFF#261]
![image](https://github.com/Parik27/DragonFF/assets/57035112/66c25fbb-6096-4315-bf57-32c80ba22ed4)
![image](https://github.com/Parik27/DragonFF/assets/57035112/4b44c88d-db38-4da4-863d-4d3062e17b38)
![image](https://github.com/Parik27/DragonFF/assets/57035112/6bcf97ba-91df-4917-8dd7-ed2f58932875)
![image](https://github.com/Parik27/DragonFF/assets/57035112/f5c5cc5e-5e5a-4d31-be6b-11d33fb27c3a)
blender version 3.6.4
 I've read that this is caused by the order the materials are in
but this seem unsolvable.

**Comment by Parik27** [comment]
This is not caused by the order of the materials since it seems it's just one object. It more likely seems like a backface culling issue looking at the model. Make sure that the model is solid (i.e not just a plane) or else it won't be visible when viewing it from behind.

**Comment by johnnie-br** [comment]
> This is not caused by the order of the materials since it seems it's just one object. It more likely seems like a backface culling issue looking at the model. Make sure that the model is solid (i.e not just a plane) or else it won't be visible when viewing it from behind.

By the way, I see that many people have a similar problem with the backface not working. Would it be possible to add an option to export the models by forcing backface culling? Or maybe I'll adding instructions on how to avoid such problems when exporting a model? It would really be useful, and probably many would greatly appreciate it.

**Comment by Amir1386kazemi** [comment]
@johnnie-br 
would you please explain how to avoid this problem

**Comment by johnnie-br** [comment]
> @johnnie-br 
> would you please explain how to avoid this problem

I don't even know how to do it

**Comment by johnnie-br** [comment]
> @johnnie-br 
> would you please explain how to avoid this problem

I don't even know how to do it
