### ISSUE TITLE
Add-on doesn't install

### ISSUE THREAD

**Issue by tmfksoft** [Parik27/DragonFF#262]
When selecting the ZIP archive from the install option in Blender 4.0 (I've tried the same in Blender 3.3.1)
I get the following log:
![image](https://github.com/Parik27/DragonFF/assets/4118296/2dc558ce-0bc8-402d-9554-c9ec3fe4eb1c)

The addon doesn't show in the list of addons and checking Blenders log window shows nothing more than that log line.

I'm not sure whats wrong?

Any ideas?

**Comment by tmfksoft** [comment]
I forgot to check an older verion of DragonFF, the previous commit (a0762b67e1157e29d382b85df1ecbc3845db73f6)
Seems to load fine, not tested it as I write this but whatever has changed, which appears to be very little seems to break importing the addon for me.

**Comment by Parik27** [comment]
The previous and the latest commit are the same. Nothing changed between the two commits.
