### ISSUE TITLE
Support for Bully PlayStation 2 .dff models

### ISSUE THREAD

**Issue by RecklessGlue540** [Parik27/DragonFF#265]
It would be nice to have support for the original Bully in the future...
Anyway, I've provided a sample here: https://www.mediafire.com/folder/9zfqhlmrplm3c/PS2 (I've also included the .txd if needed...)

Now, I do not know whether the Wii version uses RenderWare or not, it still appears to be using .dff and .txd in entirety, but there's no tool that can even extract contents from Wii .imgs properly... yet...

Still, PS2 support would be more than enough...
Feel free to close this, if Bully is not in scope for this project.
Nice tool by the way...

**Comment by Psycrow101** [comment]
@RecklessGlue540 You can try this https://github.com/Parik27/DragonFF/pull/250

https://github.com/Psycrow101/DragonFF/tree/native-plg or https://github.com/Psycrow101/DragonFF/tree/multi-mesh
