### ISSUE TITLE
Getting the actual lighting from in-game

### ISSUE THREAD

**Issue by iMopolo** [Parik27/DragonFF#28]
I've made a couple of animations using your addon, [but they look like I'm using enb series](https://www.youtube.com/watch?v=bpwruGM2r_g).

Is there any way to get the vertex colour and render it with eevee?

**Comment by swift502** [comment]
Sure the vertex color should be there with the models. Just look up how to use it in any Blender forum. You need to add the attribute input in your shader and fill in the name of the vertex color slot. Then you multiply the texture color with the vertex color.
