### ISSUE TITLE
weight paint issue.

### ISSUE THREAD

**Issue by jaigitrep159** [Parik27/DragonFF#288]
![Issue](https://github.com/Parik27/DragonFF/assets/76834328/d181248e-a269-48d1-8e7d-a289b9f2d1f0)
Alright, so i did attempt to port my Ruby Gillman Blender 3D Model (https://youtu.be/BPurl93cKuY) into GTA: SA using Blender 3.6.8 LTS with DragonFF (the addon). 
i import a dff file (wuzimu.dff from GTA: SA's gta3.img), and i delete the skin, 
next, i decimate my model to the lowest possible poly model, with some mesh data transfer addon. 
i setup the bones from that dff file i imported and match the reference to my character, 
did some weight painting with some automated addons, and when i export it to DFF file with the default settings with the version preset "GTA SA", the weight paint got ran into some issue.

Here's the files that you can inspect my model:
[dff](https://cdn.discordapp.com/attachments/918127490722070598/1223260042854404096/rubgil.dff?ex=661934b1&is=6606bfb1&hm=b6dfd80c7c9908f50d9eb3335ba4128d73fb1454ba65bf322e2bee64cf1c9022&)
[blend](https://cdn.discordapp.com/attachments/918127490722070598/1223260259427156140/GTA_SA_Attempt.blend?ex=661934e4&is=6606bfe4&hm=05cb1bf7b1b6a78109b8ddb925f4acef66ddd9b032d496c805d0091f4b321c56&)

**Comment by jaigitrep159** [comment]
[issue.zip](https://github.com/Parik27/DragonFF/files/14810138/issue.zip)
reuploaded with the zip file cuz discord has some expiration links.

**Comment by jaigitrep159** [comment]
![Issue2](https://github.com/Parik27/DragonFF/assets/76834328/36db0671-f84a-48c7-b56e-7ffb93724bfc)
Even decimate the model kind even more doesn't work. still the same. (down to 6K Verts)
[weightpaintissue.zip](https://github.com/Parik27/DragonFF/files/14810647/weightpaintissue.zip)

**Comment by jaigitrep159** [comment]
[weightpaintRigIssue.zip](https://github.com/Parik27/DragonFF/files/14810658/weightpaintRigIssue.zip)
forgot to pack some of the texture so here's this updated file, again.

**Comment by jaigitrep159** [comment]
umm... i think this is because of limits of splitted objects?

**Comment by jaigitrep159** [comment]
okay, so having another attempt, this time another custom skin i made, which is my OC character (J Man)
almost 2K verts. Same thing, triangulate, bone setup, weight paint, everything.
when i export it, same effect.
Version: Blender 3.6.8 LTS
![Issue3](https://github.com/Parik27/DragonFF/assets/76834328/807d9fe7-fe34-4076-a93e-f413036fc777)
[J2.zip](https://github.com/Parik27/DragonFF/files/14865423/J2.zip)

**Comment by Psycrow101** [comment]
@jaigitrep159 too many weight groups per vertex. RW can only support 4 groups per vertex and DragonFF ignores the extra ones when exporting. You can remove minor groups using Open -> Clean Up -> Clean Vertex Group Weights, setting the Limit value to 0.1.
![99CC8AA9-7380-4BCC-A20E-E852B52030CA](https://github.com/Parik27/DragonFF/assets/31922454/03da27de-d8d0-458f-a8a2-77959d0af4a6)

**Comment by jaigitrep159** [comment]
I'll try that fix you provided @Psycrow101

**Comment by jaigitrep159** [comment]
![image](https://github.com/Parik27/DragonFF/assets/76834328/d6bdee96-3907-4a44-9283-371c324ba2a2)
btw here's this in-game...

**Comment by jaigitrep159** [comment]
@Psycrow101 UPDATE: Upon importing back from the fixed dff file you provide the issue, it worked. 
But GTA SA in-game, STILL THE SAME.
![image](https://github.com/Parik27/DragonFF/assets/76834328/f73e37e5-f87a-4b8a-8655-61070b1cdfa7)

**Comment by jaigitrep159** [comment]
![gallery6](https://github.com/Parik27/DragonFF/assets/76834328/35d8e07c-1813-4c1a-adaf-f21d579f7f9a)
As for my OC model, it works, deformation looks weird, but it works.

**Comment by jaigitrep159** [comment]
Oh and by the way, how i can make the texture not shadeless?

**Comment by jaigitrep159** [comment]
![gta sa teaser](https://github.com/Parik27/DragonFF/assets/76834328/5d0d169c-4dae-4afe-80f0-b6aad2289de2)
also i tried to convert from t pose to a pose, but i think it doesn't work, i think it is because of rotation of the bones

**Comment by jaigitrep159** [comment]
Good news, i finally figured out the issue! Seems like GTA:SA/gta3.img/player.dff was the only thing that had the correct bone position and rotation. So i took that dff file, data transfer it using mesh data transfer addon, i also delete the color attribute, weight paint, cleanup, and it works perfectly well!
![gallery7](https://github.com/Parik27/DragonFF/assets/76834328/90617286-1d79-49da-bafb-b3b3f6ae5224)
![gallery8](https://github.com/Parik27/DragonFF/assets/76834328/1a41297a-f19a-496d-9851-a54da5f0215f)
Thank you @Psycrow101 for providing the fix suggestion about clean weight painting, now i can finally make custom skins using dragonff in blender without having to worry about 3ds max, a paid 3d software! Closing this issue now.
