### ISSUE TITLE
Cannot replace CS models in GTA: Vice City

### ISSUE THREAD

**Issue by GrimShaw245** [Parik27/DragonFF#300]
Hey there, I wasn't sure where else to go for this since most people who work on VC mods typically use 3DSmax, I wanted to replace a cutscene model in the game, I was successful at replacing the playable model in-game, but whenever I do cutscene models, nothing changes, and it uses the default model. I'm not sure if there is something I could be doing wrong here, but I'd like help figuring it out, thanks.

Model I want to replace CS with:
![image_2024-05-25_062418499](https://github.com/Parik27/DragonFF/assets/65777805/5e25436a-8088-429f-9ac7-f7cfa28663e4)
CS model that doesn't change:
![image_2024-05-25_062545244](https://github.com/Parik27/DragonFF/assets/65777805/93406dd6-5213-4369-815f-2d4098e7ea41)

**Comment by GrimShaw245** [comment]
I am trying to replace CSPlay using TXDWorkshop, the filesize even changes, but it still uses the default tommy for some reason

**Comment by GrimShaw245** [comment]
I have the CSplay model changed in TXDWorkshop, as well as the model rigged to CSplay, but nothing changed in-game.

![image_2024-05-28_061506457](https://github.com/Parik27/DragonFF/assets/65777805/0b203ebf-df92-4d2d-8a3f-57f11292a882)
![image_2024-05-28_061730278](https://github.com/Parik27/DragonFF/assets/65777805/95bc3330-a847-4882-a9d9-0058702e6527)

**Comment by Parik27** [comment]
Well try replacing the other models (or replacing CSPlay with other models). It doesn't look like an addon issue.

**Comment by GrimShaw245** [comment]
I tried it out with other models, and it seems that maybe it's the game itself, but what would be causing it to still not be replaced?

**Comment by GrimShaw245** [comment]
Figured out the issue and the model is now replaced for the cutscene. It had something to do with modloader for various fixes for VC, but the model also came out extremely broken for some reason. I will open up another issue page for that, but for now, this one is complete.
![image_2024-06-01_181224139](https://github.com/Parik27/DragonFF/assets/65777805/3daac497-c755-486d-9d1c-cb662bddce5c)
