### ISSUE TITLE
Read Material Split - Map Import

### ISSUE THREAD

**Issue by blckdot** [Parik27/DragonFF#304]
Is there a way to apply Read Material Split option to models that are being loaded via map import feature ? I'm trying to load a custom map, that, as I understand, was exported from 3ds max via Kam's Scripts that doesn't set the materials properly. I understand that this can be done in another way, but map import feature is just more convenient.

**Comment by Psycrow101** [comment]
Hello! Try this branch https://github.com/Psycrow101/DragonFF/tree/map-mat-split

**Comment by blckdot** [comment]
@Psycrow101, Thank you, it works, your multi-mesh branch was also very helpful
