### ISSUE TITLE
Exporting skin with version from GTA III (RW 3.3.0.2) = GTA VC (or maybe III) crashes

### ISSUE THREAD

**Issue by jaigitrep159** [Parik27/DragonFF#307]
Hey there, i've been successfully working on my Ruby Gillman Blender Model ported to GTA:SA, but one problem for GTA:VC, i exported it out with version 3.3.0.2 according to GTA:VC's player.dff model. When i try to replace it, my GTA: VC will crash. Maybe missing attributes?

Here's a comparison (left is original, and right is exported.)

![image](https://github.com/Parik27/DragonFF/assets/76834328/71d048eb-1dde-4e83-a8af-b102986cac3e)

Anybody help me to fix the issue? I'm in the latest build of DragonFF.

**Comment by jaigitrep159** [comment]
[Ruby Gillman.zip](https://github.com/user-attachments/files/15611218/Ruby.Gillman.zip)
here's the zip file, containing blend, dff and txd files.

**Comment by jaigitrep159** [comment]
![image](https://github.com/Parik27/DragonFF/assets/76834328/5b07f66b-cf4a-49bb-a6e0-778558ca60ed)
oh yeah forgot to mention, this is 3.4.0.3 (GTA VC), it's CSplay.dff from GTA Vice City/models/gta3.img. seems like Material Effects PLG and Morph PLG attributes are gone.

**Comment by jaigitrep159** [comment]
https://www.gtainside.com/en/vicecity/skins/196734-walter-white-from-breaking-bad/ DragonFF devs, can someone also test this skin to import and re-export to dragonff witb version 3.3.0.2 (GTA III RW)? normals and without normals? and check if the game is crashed? this is high poly model, sort of, the same thing goes with my ruby gillman model.

**Comment by jaigitrep159** [comment]
@Psycrow101

**Comment by Psycrow101** [comment]
I'll take a look at it tomorrow

**Comment by Psycrow101** [comment]
The armature in player.dff in the attached archive is corrupted, but GTA VC Attempt.blend is exported normally. Not sure if missing attributes cause the game to crash. Have you tried exporting for version 3.4.0.3 (GTA VC)?

**Comment by Psycrow101** [comment]
@jaigitrep159 try the latest update
https://github.com/Parik27/DragonFF/commit/f2ec25c1a9c3a441f3dd86ff4f6020fc2d963d4e
