### ISSUE TITLE
When exporting a custom GTA III Skin, the rotation seems fricked up. Is there a fix?

### ISSUE THREAD

**Issue by jaigitrep159** [Parik27/DragonFF#312]
![Screenshot (1)](https://github.com/Parik27/DragonFF/assets/76834328/8a4a6d3e-d6bc-4093-8c2e-18a348ac3c3d)
![Screenshot (2)](https://github.com/Parik27/DragonFF/assets/76834328/4a48382f-de26-49c0-b62b-0bf2e71ffe86)
[issue.zip](https://github.com/user-attachments/files/15858157/issue.zip)

Using Blender 3.6.8 LTS, with the latest build of DragonFF (RenderWare version bug fix update)

**Comment by jaigitrep159** [comment]
i think it MAY had something to do with rotation matrix thing. I did the parent correct EXACTLY like Claude's rig structure.

**Comment by jaigitrep159** [comment]
when i import GTA III's playerp.dff, re-export to DragonFF and put it to my modloader folder, it works as it normally would. it's so weird that it has to do with matrix rotation. Probably using world space or local space idk...

**Comment by Parik27** [comment]
Have you applied transformations in Blender?

**Comment by jaigitrep159** [comment]
> Have you applied transformations in Blender?

Don't you mean Ctrl+A and then apply all transforms?

**Comment by jaigitrep159** [comment]
I have applied scale and rotation transformations, here's the result:
![Screenshot (7)](https://github.com/Parik27/DragonFF/assets/76834328/f2e64f5d-082e-4d2b-b41d-93475c37ac18)
![Screenshot (8)](https://github.com/Parik27/DragonFF/assets/76834328/93e8adff-99fb-4793-a330-ef1343d6cbb3)

**Comment by jaigitrep159** [comment]
@Parik27

**Comment by jaigitrep159** [comment]
I'm still open this issue, it's been last month and hasn't fix yet.

**Comment by jaigitrep159** [comment]
It's August, yet still didn't fixed yet. I have provided an issue.zip file shown above if someone debugging this and fix it.

**Comment by Calvin-rgb** [comment]
It's the holiday season and a great time to relax, apparently the addon developers are not at work

**Comment by Parik27** [comment]
There doesn't seem to be anything to fix. You said yourself that exporting the normal dff works, therefore this likely isn't an issue with the exporter. Compare the normal dff and your own and see what's different and try to match it as close as possible.

**Comment by jaigitrep159** [comment]
i'll try i guess

**Comment by Psycrow101** [comment]
@jaigitrep159 You have the wrong frame order. You can change the order using [this DragonFF branch](https://github.com/Psycrow101/DragonFF/tree/mm-objects-order).

![image](https://github.com/user-attachments/assets/d4a1191d-3ebe-4af3-a292-4cd8ef65d326)

How it looks in the game after reordering:
![image](https://github.com/user-attachments/assets/8198ec89-ec93-4f26-8947-7d7df2ee2cc8)

Correct frame order:
* playerp
* Swaist
* Smid
* Supperlegl
* Supperlegr
* Slowerlegr
* Sfootr
* Slowerlegl
* Sfootl
* Storso
* Supperarml
* Supperarmr
* Shead
* Slowerarmr
* SRhand
* Slowerarml
* SLhand


[playerp.zip](https://github.com/user-attachments/files/16922165/playerp.zip)
