### ISSUE TITLE
question about LOD (GTA SA)

### ISSUE THREAD

**Issue by scorp2007** [Parik27/DragonFF#315]
Hello, I'm trying to load a GTA SA map into blender, but I noticed that if I load all the objects, they have terrible quality because of the LOD, and if I check the "Skip LOD" checkbox, then only a small part of the objects are loaded. Do I understand correctly that now there is no way to load all objects in normal texture quality? Thanks.

**Comment by planetgummy** [comment]
Use #308 to import SA maps.

**Comment by scorp2007** [comment]
> Use #308 to import SA maps.

Thank you, by the way, I saw this topic, but I thought by merging the thread you had already built this feature into the new version, I downloaded it, but it had the same problem. Please explain how I can use this? Should I do any additional steps?

**Comment by planetgummy** [comment]
In the dropdown where you choose which part of the map you want to import, it should now have the binary IPLs listed, like lae2_stream0, lae_stream1, lahills_stream0, etc...

**Comment by scorp2007** [comment]
> In the dropdown where you choose which part of the map you want to import, it should now have the binary IPLs listed, like lae2_stream0, lae_stream1, lahills_stream0, etc...

Thank you, I did it
