### ISSUE TITLE
The raindrops enter the object that i created

### ISSUE THREAD

**Issue by darkerthanyin** [Parik27/DragonFF#319]
I created a small saloon object for GTA SA in Blender using the DragonFF plugin. However, after testing it in the game, I noticed that when it rains, the raindrops enter the interior of the saloon. Is there a solution for this?

![image (1)](https://github.com/Parik27/DragonFF/assets/173225968/6102b436-3b56-4432-8045-88bee243ea09)

**Comment by YOEL-44** [comment]
That is controlled by cull zones, not models, check this documentation.
https://gtamods.com/wiki/CULL
