### ISSUE TITLE
Randomly flipped tris for imported map objects

### ISSUE THREAD

**Issue by jgooderham** [Parik27/DragonFF#322]
Here you can see a shading issue on the street where CJ's house resides:
![image](https://github.com/Parik27/DragonFF/assets/728467/618bb8bf-88af-45e0-af26-af2dae2ddd41)
Flipping on face orientation in the viewport overlays shows that some tris have the wrong orientation:
![image](https://github.com/Parik27/DragonFF/assets/728467/5338a957-60a4-4cbc-a3ca-26823f1c54eb)
And applying a normals recalculation in Blender resolves the issue:
![image](https://github.com/Parik27/DragonFF/assets/728467/087fc75f-11e7-4b9d-8e44-7152dc76dab6)
This issue is present on a lot of imported map objects:
![image](https://github.com/Parik27/DragonFF/assets/728467/5264b917-b9a1-4351-8bc8-2ccb485dcc70)
While it's easy enough to fix in-place with a normals recalculation, I wonder if anyone has an idea what would be causing the flipping? I thought maybe it was an issue with triangle strips, but I couldn't find anything. It would be nice to solve this. I don't actually know if this is a format limitation or an actual issue with how objects are imported. The export menu for objects says to disable "Export normals" for map objects. So do they just not even have normals? If you export this mesh without fixing the orientations, the backfaced tris do get culled in-game so the game does recognize their orientation. If it's a format issue then we could automatically apply the recalculate normals function from Blender on import. I'm not familiar enough with modding to know though.

**Comment by Psycrow101** [comment]
Hi. Pay attention to these code sections:
https://github.com/Parik27/DragonFF/blob/master/ops/map_importer.py#L108
https://github.com/Parik27/DragonFF/blob/master/ops/dff_importer.py#L635

Try disabling the "remove_doubles" option. I'm guessing that some meshes have duplicate faces with opposite sides. Blender tries to remove duplicate vertices and ignores the triangles' orientation, which can cause this behavior

**Comment by jgooderham** [comment]
Thank you for this. I'm going to take a look at it when I can.

**Comment by jgooderham** [comment]
Man so you know what's weird? This isn't even an issue in Blender 4.1. I had been developing on Blender 3.0. Not for any real reason other than it was what was installed on my machine. After I upgraded that visual noise is gone, even though the same flipped tris remain. I still think that's not ideal but I dunno, I guess this isn't really an issue anymore.
