### ISSUE TITLE
Incorrect calculation of bounding box and sphere box on vehicles

### ISSUE THREAD

**Issue by Shuubaru** [Parik27/DragonFF#327]
Calculation of both bounding box and bounding spheres in vehicles is wrong which causes features like fake ground shadow to look weird on some custom vehicles.

Left: exported with another tool - Right: exported with DragonFF

![image](https://github.com/user-attachments/assets/342c8c65-0134-46a9-8aaf-131f1b6cbe24)

inb4 "check your model again for mistakes", this can also be reproduced with vanilla vehicles, i.e with Benson:

Left: Vanilla - Right: Exported from DragonFF without any further edit
![image](https://github.com/user-attachments/assets/cf1ef628-6b18-4d6c-8882-81a80be262cc)

**Steps to reproduce with latest DragonFF version downloaded from this repository, and Blender 3.6.5:**
1- Import a vanilla vehicle i.e Benson.
2- Export it back without any extra edit.
3- Export the embedded COL3 collision file from both the vanilla and the exported vehicles and compare them in COL Editor II.
4- You can clearly see the differences below:
![Captura de pantalla (283)](https://github.com/user-attachments/assets/112dfafb-e6cc-47ac-96e9-09d356d4252d)
![Captura de pantalla (284)](https://github.com/user-attachments/assets/865e48d1-5c33-4dc8-8e08-6801eb7fbbc0)

While COL Editor II can already recalculate the bounding sphere and box properly by doing **Right Click > Bounds > Optimum** an in-blender solution would be good. What solution I propose? The solution GTA Tools addon has. This old addon for blender 2.79 let us to preview both Boundings in Blender so we can freely choose the size and position of both boundings which prevents any extra headache caused by automatic calculations:
![image](https://github.com/user-attachments/assets/4d482ad2-6a6e-4fee-82c2-e2b8e2b11b0c)

**Comment by Parik27** [comment]
Please check if the automatic bounds calculation is fixed in #316

**Comment by Shuubaru** [comment]
> Please check if the automatic bounds calculation is fixed in #316

@Parik27 Tested with that build and it works great on both custom and vanilla vehicles!
Thanks for the help and also thanks to @jgooderham for fixing this issue.
![image](https://github.com/user-attachments/assets/d795ac80-94b0-423d-b088-e7c10e2a07c6)
![image](https://github.com/user-attachments/assets/11d407bf-542a-496f-95ab-a7c92f20161f)

**Comment by jgooderham** [comment]
Awesome to hear and thanks for testing that. Yea I'm still working on that PR but I'm nearly there. I've just had a lot of work lately. I'm trying to get face group display/generation done (although that's more of a map object thing). But with that we should have pretty much all of the features of collision files implemented so it should be a good addition to the addon.

**Comment by Shuubaru** [comment]
Tested again with the master branch and the issue seems to resolved after the merge, so I'm closing the issue now.
