### ISSUE TITLE
Error When Exporting Dragon F F GTA Model

### ISSUE THREAD

**Issue by A-for-AMIR** [Parik27/DragonFF#328]
I Have A Problem When Export Some Model
Change My Blender And Addon Dragon F F But It's Only Give Me Error
-----------------------------------
![image](https://github.com/user-attachments/assets/4e7bb5c9-05aa-4237-af28-79569a7a2101)
-----------------------------------
Pls Help Me!

**Comment by A-for-AMIR** [comment]
I Fix The Issue But Get New Errors
----------------------------------
![image](https://github.com/user-attachments/assets/e34779ee-6313-43ee-9ccb-90d39d2c0661)
-----------------------------------

I Didn't Sleep Last night For This ***

**Comment by Parik27** [comment]
What version of DragonFF is this? Does the master branch one work?

**Comment by A-for-AMIR** [comment]
I Don't Know What's The Version But I Just Download It
----------------------
[DragonFF-master.zip](https://github.com/user-attachments/files/16303730/DragonFF-master.zip)
----------------------

**Comment by Psycrow101** [comment]
You didn't specify a file name

**Comment by A-for-AMIR** [comment]
If You Have Free Time Please Help Me To SetUp My Blender With DragonDff

**Comment by Psycrow101** [comment]
Try install the latest version and export again
