### ISSUE TITLE
I can't export my custom dff

### ISSUE THREAD

**Issue by pepengi** [Parik27/DragonFF#330]
Whenever I go to export a dff created by me, I always get this "Finished export in 0.00s", but if I import a model from the game and export it again, it will export
![image](https://github.com/user-attachments/assets/d62c2044-557b-464c-b541-803909003ebc)
![image](https://github.com/user-attachments/assets/513106a3-4068-48c2-bcfb-e788f070a944)
![image](https://github.com/user-attachments/assets/8a44a6cd-20ff-4400-9536-da85ee3c8724)

**Comment by Psycrow101** [comment]
@pepengi Try renaming the collection to "griffi.dff"

**Comment by jgooderham** [comment]
Hey there. Sorry but this was an unintended result of some changed I submitted a few days ago. I posted a fix here #331 if you wouldn't mind testing it to make sure everything is good again. Thanks.
