### ISSUE TITLE
Transparency and double-sided issues

### ISSUE THREAD

**Issue by j0hnn1e20** [Parik27/DragonFF#332]
![image](https://github.com/user-attachments/assets/0f2cd214-dc36-46fd-b3ef-faeb58667c63)
I have a model ready, correctly made and everything adjusted, however, there are problems with buggy glasses not showing elements correctly
![image](https://github.com/user-attachments/assets/cd3ce51f-aea9-417c-8077-2d24dbdd2eab)

**Comment by NaufalFajri** [comment]
select all mesh
go to edit mode
select all transparent & alpha material
invert & hide
duplicate shift+d on 0 position
invert & delete vertices

**Comment by Amir1386kazemi** [comment]
did you found a solution ?

**Comment by jonatasfsj** [comment]
Ah, Yeah!

You need to separate glass of doors, and place them below the doors in the hierarchy
