### ISSUE TITLE
Sorting the hierarchy

### ISSUE THREAD

**Issue by by-tndy** [Parik27/DragonFF#334]
What is the principle of sorting the hierarchy of objects during import and export? and is it possible to change their location?
![image](https://github.com/user-attachments/assets/63746e55-4e99-4885-a6ad-2754252b4404)

**Comment by by-tndy** [comment]
Ого, даже в новое усовершенствование отметили. Тогда если будет возможность, добавьте так же учитывание положении материалов иерархии, так как оно при экспорте так же не учитывает. 
К примеру, все прозрачные материалы должны быть в конце списка материалов, что бы не было просвечивания через другие. 

Wow, even a new improvement was noted. Then, if possible, add the same consideration for the position of the hierarchy materials, since it also does not take into account when exporting. 
For example, all transparent materials should be at the end of the list of materials, so that there would be no transmission through others.

@Psycrow101

**Comment by Psycrow101** [comment]
In the current version of Blender, it is not possible to change the order of objects in the hierarchy at one level. DragonFF exports objects in the order in which they are created in the scene. Therefore, the order will be preserved until a new object is added.

I have started to develop an interface for sorting atomics and frames to solve this issue. You can try it in the new branch ["objects-order"](https://github.com/Psycrow101/DragonFF/tree/objects-order)

![image](https://github.com/user-attachments/assets/07d6f4dc-ed46-4881-acde-5be9129784c0)

One big list can be quite inconvenient for a complex hierarchy, but I will try to somehow expand the interface, for example by adding filtering by collections.

**Comment by by-tndy** [comment]
> In the current version of Blender, it is not possible to change the order of objects in the hierarchy at one level. DragonFF exports objects in the order in which they are created in the scene. Therefore, the order will be preserved until a new object is added.
> 
> I have started to develop an interface for sorting atomics and frames to solve this issue. You can try it in the new branch ["objects-order"](https://github.com/Psycrow101/DragonFF/tree/objects-order)
> 
> ![image](https://private-user-images.githubusercontent.com/31922454/364158821-07d6f4dc-ed46-4881-acde-5be9129784c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0Mjc3NTUsIm5iZiI6MTcyNTQyNzQ1NSwicGF0aCI6Ii8zMTkyMjQ1NC8zNjQxNTg4MjEtMDdkNmY0ZGMtZWQ0Ni00ODgxLWFjZGUtNWJlOTEyOTc4NGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDA1MjQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1OTE4ZDk5NmZiYzk2ZjNjMDMzMTYxNWU0NjIxNmIyMzYzYjRiYzdkODdhOWE5Y2MyYTllOTg1NWM3OTlmMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a7DZSIDoBaQhmyM1ESWxyoGutrT5WTsjGbfVG8rlkcU)
> 
> One big list can be quite inconvenient for a complex hierarchy, but I will try to somehow expand the interface, for example by adding filtering by collections.

Great. Then I think it's not worth closing this topic, for feedback from this branch

**Comment by by-tndy** [comment]
> Therefore, the order will be preserved until a new object is added

Is it possible to implement this without adding an object? because there are cases when it is necessary to edit the model without adding a new object.

**Comment by Psycrow101** [comment]
> > Therefore, the order will be preserved until a new object is added
> 
> 
> 
> Is it possible to implement this without adding an object? because there are cases when it is necessary to edit the model without adding a new object.

You can change the order of objects without creating a new one

**Comment by by-tndy** [comment]
> You can change the order of objects without creating a new one

Unfortunately, this does not work, when moving and exporting, it is not saved
![blender_bpJFF9bgGh](https://github.com/user-attachments/assets/cd13aaa9-fb3d-4870-99a8-76a198421a5f)

**Comment by by-tndy** [comment]
> Если создать новый объект, то он будет экспортирован в самом конце. В изменённой версии DragonFF можно изменять порядок как для новых объектов, так и для старых, если при экспорте их порядок по какой-то причине нарушился

ты прав, он экспортирует в том случаи если галка сортировка по имени отключена, но это работает не постоянно. Я так и не понял принцип к сожалению

**Comment by by-tndy** [comment]
> > > Therefore, the order will be preserved until a new object is added
> > 
> > 
> > Is it possible to implement this without adding an object? because there are cases when it is necessary to edit the model without adding a new object.
> 
> You can change the order of objects without creating a new one
> 
> Я имел в виду, что DragonFF теоретически экспортирует объекты в том порядке, в котором они были импортированы (за исключением некоторых случаев). Если создать новый объект, то он будет экспортирован в самом конце. В изменённой версии DragonFF можно изменять порядок как для новых объектов, так и для старых, если при экспорте их порядок по какой-то причине нарушился

Ч то вообще ничего не работает. Уже даже объект добавил, переместил, все равно не учитывается его положение в иерархии, при импорте обратно новый объект ставиться где угодно, но не там где нужно.

**Comment by Psycrow101** [comment]
> Unfortunately, this does not work, when moving and exporting, it is not saved 

New branch: https://github.com/Psycrow101/DragonFF/tree/mm-objects-order

Keep in mind that this is a branch of "multi-mesh" and the hierarchy of objects when imported is different from the master branch

**Comment by by-tndy** [comment]
> New branch: https://github.com/Psycrow101/DragonFF/tree/mm-objects-order
I tried it, it still doesn't work with the finished model.

**Comment by by-tndy** [comment]
> New branch: https://github.com/Psycrow101/DragonFF/tree/mm-objects-order

I tried it, it still doesn't work with the finished model.

**Comment by by-tndy** [comment]
I partially figured it out. Sometimes it works correctly when dff contains only objects, without dummy and objects in them. We need to fix this

**Comment by Psycrow101** [comment]
> I partially figured it out. Sometimes it works correctly when dff contains only objects, without dummy and objects in them. We need to fix this

[Updated](https://github.com/Psycrow101/DragonFF/tree/mm-objects-order). It should work now

**Comment by by-tndy** [comment]
> [Updated](https://github.com/Psycrow101/DragonFF/tree/mm-objects-order). It should work fine now

The down button in frames is not working, it gives an error, the up button is working.
![image](https://github.com/user-attachments/assets/da52501a-fc83-4469-8447-1f8780a10e02)

**Comment by Psycrow101** [comment]
> The down button in frames is not working, it gives an error, the up button is working.

The children_recursive method was introduced in Blender 3.1.0. Fixed for older versions

**Comment by by-tndy** [comment]
> > The down button in frames is not working, it gives an error, the up button is working.
> 
> The children_recursive method was introduced in Blender 3.1.0. Fixed for older versions

Damn it, it works. I will be waiting for this opportunity in the main branch.
![image](https://github.com/user-attachments/assets/4e4da72f-6109-4f04-8573-276848f03e98)
![image](https://github.com/user-attachments/assets/2cdce47a-aae6-450f-9505-920a22fdb9a2)

Ты крут мужик

**Comment by by-tndy** [comment]
Is it possible to display objects in the hierarchy in the same way as in the master branch? because they are all in dummy, it is a little inconvenient to navigate

**Comment by Psycrow101** [comment]
> Is it possible to display objects in the hierarchy in the same way as in the master branch? because they are all in dummy, it is a little inconvenient to navigate
> 
> А лучше я думаю сделать единую панель, как для dummy так и для mesh, по значку пустышки и объекта спокойно можно отличить

Yes, in the next update I will try to simplify the hierarchy.

К сожалению, сделать единую панель не получится, если я правильно понял. Для некоторых моделей из других игр необходимо строгое разделение. Такая иерархия была сделана по этой причине https://github.com/Parik27/DragonFF/pull/337. Но для таких моделей, как bmx, все еще возможно вернуться к тому, что было в основной ветке.

**Comment by by-tndy** [comment]
> Но для таких моделей, как bmx, все еще возможно вернуться к тому, что было в основной ветке.

Если это не будет вызывать конфликты, конечно возвращай, но если будет вызывать конфликты - тогда не стоит, на данном этапе оно работает и так, просто не совсем удобно, я всё же за унификацию ибо renderware на одной gta 3d вселенной не закончился. 
Думаю можно сделать небольшой faq, ибо есть ньюанс при сортировки иерархии, в ветке mm-objects-order, если положения mesh'a и dummy (в случаи если имя mesh и dummy совпадают, к примеру в том же bmx что относиться к транспорту) нужно их выставить в строгом порядке 1 к 1 (не распространяется на тип dummy типа света headlights, ped_frontseat и т.п, в общем все dummy который только указывают положения ибо они всегда идут первыми в иерархии). Если нужна будет помощь, я смогу написать эту памятку при добавления в master ветку фичи

**Comment by Calvin-rgb** [comment]
> > Но для таких моделей, как BMX, все еще возможно вернуться к тому, что было в основной ветке.
> 
> Если это не будет исходом конфликтов, конечно, временным, но если тогда будет возникновение конфликтов - не стоит, на данном этапе оно работает, и так, просто не совсем удобно, я всё же за унификацию программного обеспечения рендеринга в одной вселенной GTA 3D не закончилась. Я думаю, можно сделать небольшой FAQ, если есть новые события при сортировке иерархии, в ветке mm-objects-order, если положения mesh'a и dummy (в тех случаях, если имя mesh и dummy совпадают, например, в том же bmx, что необходимо для транспортировки) их выставляют в строгом порядке 1 к 1 (не относятся к типам манекенов типа световых фар, ped_frontseat и т.п, в общем все манекены, которые только указывают положения, они всегда идут первыми в иерархии). Если понадобится помощь, я смогу написать это воспоминание при добавлении в мастер-ветку фичи.

Можешь создать страничку на вики к этому репозиторию
Будет полезно для коммюнити

**Comment by by-tndy** [comment]
> Now the object tree is as short as possible. An object can be exported as a frame using a new item in the object properties.

я нич не понял, как этим пользоваться и зачем оно надо?

**Comment by Psycrow101** [comment]
> > Now the object tree is as short as possible. An object can be exported as a frame using a new item in the object properties.
> 
> я нич не понял, как этим пользоваться и зачем оно надо?

Если галка установлена, то объект будет экспортирован как frame и atomic, ссылающийся на на этот frame. Если не установлена, то будет просто atomic, ссылающийся на родительский frame.

Пример frankie.dff из GTA III. У него 20 фреймов и 4 атомиков. 16 фреймов составляют скелет. Первый фрейм - пустышку можно проигнорировать.
![image](https://github.com/user-attachments/assets/46056ab2-fbc3-4371-962b-abcb045218e7)

Первый атомик (**mesh**) указывает на фрейм (**Swaist**), который является скелетом. Меш и скелет - 2 разных объекта, которые нельзя объединить в один. Поэтому тут галка снята.
![image](https://github.com/user-attachments/assets/939648aa-604c-4d11-8316-4665f482f7ee)

Второй атомик указывает на фрейм (**Shead01**), который в свою очередь является дочерним фреймом от **Shead**. Т.к. **Shead01** - пустышка, ее можно объединить с мешем и получить только один объект. Поэтому для **Shead01** установлен флажок, означающий, что объект **Shead01** является и атомиком, и фреймом одновременно.

![image](https://github.com/user-attachments/assets/8e666688-a86e-42f8-8420-50dd5eecd22f)

Если снять флажок и экспортировать, то получится, что атомик указывает на **Shead**, а фрейм **Shead01** отсутствует. 

Разумеется при импорте нужные флажки будут установлены автоматически и на них можно не обращать внимания, если нет необходимости создавать новый объект для модели. Они помогают правильно интерпретировать объекты при экспорте.

В некоторых случаях меши нельзя объединить с пустышками. Например, когда на один фрейм указывают несколько атомиков. Тогда фрейм импортируется как пустышка, которая является родителем атомиков на сцене. Галка в таком случае снята.

**Comment by Psycrow101** [comment]
Теперь если импортировать bmx.dff, то дерево объектов в аутлайнере будет как в master-ветке

![image](https://github.com/user-attachments/assets/73e16d89-33dc-406f-94ef-ba98cf13f8a8)

Здесь каждую меш-атомик можно объединить с фреймами, на которые они указывают. Таким образом иерархия становится более компактной
