### ISSUE TITLE
Change the behavior of some export options

### ISSUE THREAD

**Issue by Psycrow101** [Parik27/DragonFF#339]
I have a few suggestions to change the behavior of some export options:

1. Set "preserve positions" for root frame only. As I understand it, this option is needed to export an object without applying transformation during map importing. If this is true, then why are the positions reset for all frames? I think this feature should only affect the frame with zero (root) index as it does when importing a map. https://github.com/Parik27/DragonFF/blob/master/ops/dff_exporter.py#L327
2. Change "preserve positions" to "preserve transformations" for preserve rotation and scale.
3. Use collection name instead of object name as default file name for export from outliner. If the collection is not defined, then use the object name.
https://github.com/Parik27/DragonFF/blob/master/gui/dff_ot.py#L180

If you agree with these changes, I can make them in the next version of DragonFF

**Comment by Calvin-rgb** [comment]
Good idea!

**Comment by Parik27** [comment]
1. Seems to be an oversight yeah.
2. Maybe there could be separate options for each?
3. I think this change has already been implemented

**Comment by Psycrow101** [comment]
> 3. I think this change has already been implemented

Yes, 3 has already been implemented
