### ISSUE TITLE
Discord Channel

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#340]
Decided to create a discord channel for our community of users of this addon
[Link](https://discord.gg/j2SpX4Aj)

**Comment by Psycrow101** [comment]
@Parik27 how about adding this link to README.md?

**Comment by Calvin-rgb** [comment]
Optionally, you can create a web hook so that each commit is displayed in the discord channel

**Comment by Gabbrieh** [comment]
> Decided to create a discord channel for our community of users of this addon [Link](https://discord.gg/j2SpX4Aj)

Hello! I would like to enter the discord, but unfortunately the link expired. Could you pass it again?

**Comment by Parik27** [comment]
> > Decided to create a discord channel for our community of users of this addon [Link](https://discord.gg/j2SpX4Aj)
> 
> Hello! I would like to enter the discord, but unfortunately the link expired. Could you pass it again?

Use the link at top of the readme (the discord badge)
