### ISSUE TITLE
Incorrect position of normals in .COL

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#341]
A long-standing problem with the COL exporter is that it turns the correct normals in the final model of the COL file

It is solved by turning the normals in the opposite direction, but this is not the correct behavior
![CollEditor2_65pANYkSJY](https://github.com/user-attachments/assets/44595bd3-d891-48ee-ae1c-a0c0543ef5df)

**Comment by Psycrow101** [comment]
@Calvin-rgb try this https://github.com/Parik27/DragonFF/tree/col-mesh-normals

**Comment by Calvin-rgb** [comment]
> @Calvin-rgb try this https://github.com/Parik27/DragonFF/tree/col-mesh-normals

It works! I think it can be merged with the main master branch
