### ISSUE TITLE
Bug with txd feature

### ISSUE THREAD

**Issue by Manu2001tek** [Parik27/DragonFF#342]
I've encountered a bug with txd feature in dragonff, DFFs and TXD are in the same folder but the textures are not loaded. Ingame the map works well, textures in blender are black 
![WTF](https://github.com/user-attachments/assets/f8e58d09-660b-45ef-ad54-dbfe3ebb65b2)
before the map loaded in blender, now textures are black
it's so weird, because im making the cols and i need textures and i dont know how to fix.

**Comment by elcascavel** [comment]
Have you tried extracting the textures from the TXD file using MagicTXD and then importing the model?

**Comment by Manu2001tek** [comment]
> Have you tried extracting the textures from the TXD file using MagicTXD and then importing the model?

Yes, i've tried too

**Comment by Psycrow101** [comment]
@Manu2001tek go to Edit/Preferences/System and set "Texture Time Out" to 0
