### ISSUE TITLE
Strange behavior of the COL exporter

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#343]
Scene hierarchy:
![image](https://github.com/user-attachments/assets/31189c36-65be-4458-a49e-7ffd2c60023d)

I export an object named "polygon" nested in a collection "polygon_rccd.dff" to a COL file, and after opening it I see that the collision is duplicated only with different names
![image](https://github.com/user-attachments/assets/adebcabd-e29e-499a-ae92-7f3da069286c)

**Comment by Calvin-rgb** [comment]
The problem remains, only now it captures even more collections in COL

**Comment by Calvin-rgb** [comment]
![image](https://github.com/user-attachments/assets/a4ca4586-6907-4f69-9c60-0a6ec3d94c6c)

**Comment by Psycrow101** [comment]
Try this branch https://github.com/Parik27/DragonFF/tree/new-col-export

**Comment by Psycrow101** [comment]
Solved by https://github.com/Parik27/DragonFF/commit/4e9fc227dd43f076c444719449d874284879432b
