### ISSUE TITLE
Problem with the Map Import of Gta San Andreas

### ISSUE THREAD

**Issue by Gabbrieh** [Parik27/DragonFF#344]
Good morning. I have a problem with the Map Import function, it places all the routes correctly, but when I press the import button on the map selection, it stays loading and only loads Blender collections. I will show what was said below.

I look forward to possible solutions, thank you :)

![image](https://github.com/user-attachments/assets/d8ed972a-3515-4a70-8d0d-3b90b02b6d28)

**Comment by Psycrow101** [comment]
Are there any error messages in the console output?

**Comment by Gabbrieh** [comment]
No, no mistake. It follows the process correctly loading but it does not load the dff, as I show in the image.

**Comment by Psycrow101** [comment]
What is contained in the system console (Window -> Toogle System Console) after pressing the import button? Also what is in the directory you specified in the "Dff Folder" field?

**Comment by Calvin-rgb** [comment]
You have not specified the path to the DFF models, select the directory and everything will work

**Comment by Gabbrieh** [comment]
In the directories I have selected first the game folder, secondly a blender folder, which allows them to be imported. I don't know if it is correct, but otherwise an error appears in the console. The problem is that it takes the import action but the .dff is missing.

Could you tell me correctly how to configure it?

**Comment by Psycrow101** [comment]
@Gabbrieh In the "Dff Folder" field you should specify the path to the directory where you unpacked the files from .img (gta3.img for example). DragonFF does not currently support IMG, so you will have to unpack it yourself.

**Comment by Gabbrieh** [comment]
> @GabbriehEn el campo "Carpeta Dff" debes especificar la ruta al directorio donde descomprimiste los archivos .img (gta3.img por ejemplo). DragonFF actualmente no es compatible con IMG, por lo que tendrás que descomprimirlo tú mismo.

That was wrong, thank you. You solved my life :)
