### ISSUE TITLE
Bug in the game after editing the model

### ISSUE THREAD

**Issue by serand2048** [Parik27/DragonFF#347]
I noticed that when editing some models and their export, some polygons disappear in the game. I want to figure out what is the problem and use this plugin without such "oddities"
![gta_sa_zC6RiCtjsT](https://github.com/user-attachments/assets/5ee9dffc-4e6f-4dd2-ae20-7c432d28e0aa)

**Comment by kamikami333** [comment]
Are the polygons reddish?
Check the orientation of the faces.
![Screenshot 2024_11_08 15_33_18](https://github.com/user-attachments/assets/0d435418-1fd1-4c15-b300-65166f3819a2)

**Comment by serand2048** [comment]
Thanks, that helped. Now I want to clarify: how can I make this part render on both sides?

**Comment by elcascavel** [comment]
> Thanks, that helped. Now I want to clarify: how can I make this part render on both sides?

Like mpPako said, duplicate the geometry and flip its normals on the other side.

**Comment by Psycrow101** [comment]
Is this issue still relevant?

**Comment by serand2048** [comment]
I think we can close this issue. I don't use a blender now, I'm new to github and only yesterday I saw the Close Issue button. Thank you all for your help
