### ISSUE TITLE
[Error] Collision export function does not work (.COL)

### ISSUE THREAD

**Issue by dmsass** [Parik27/DragonFF#35]
I decided to try out the new collision export function, created an object, exported it with the _"Export Collision"_ option, and also a file with the same name as **.dff** with the **.col** extension only. Nothing is displayed in **ColEditFile II**, not even a mesh.

**Note:** _both files (.dff and .col) are named by the same name both in the operating system and in the 3D editor (Outlener)._

In ColEdit II:

![image](https://user-images.githubusercontent.com/52075975/79467696-43a2a080-8028-11ea-915e-c6bf9ae10bc6.png)

Blender3D:
![image](https://user-images.githubusercontent.com/52075975/79465652-d68e0b80-8025-11ea-9ee2-62eb15f2bc90.png)

How I exported an object (Example):
![image](https://user-images.githubusercontent.com/52075975/79466307-9a0edf80-8026-11ea-9e2e-80ab26e62a7e.png)
![image](https://user-images.githubusercontent.com/52075975/79466495-dfcba800-8026-11ea-8287-fa0082fdcc27.png)

**Comment by Parik27** [comment]
You have to create a collision object to export a collision file, to do this, you can duplicate your mesh and set its type (in the object properties) to collision object. This is equivalent to what kdff does.

**Comment by dmsass** [comment]
Ok thanks, but how to bind a collision file with an object file .dff? @Parik27

**Comment by dmsass** [comment]
I found a solution to this problem, it is necessary that collections (col and dff) have the same name. @Parik27

**Comment by Parik27** [comment]
In the original game, you need to name them the same as the dff, yeah. I'll have a script to automatically generate the col file in the future.

Is it alright to close the issue now?

**Comment by dmsass** [comment]
Yes of course, thanks for the help!
