### ISSUE TITLE
Left Headlight and taillight Inverted in-game GTA SA

### ISSUE THREAD

**Issue by Noob-dev21** [Parik27/DragonFF#351]
My left headlight and taillight is inverted in game, but the right side is ok
(New to making cars from scratch)

**Comment by Noob-dev21** [comment]
![Uploading Screenshot 2024-12-10 124152.png…]()

**Comment by Noob-dev21** [comment]
![Screenshot 2024-12-10 124128](https://github.com/user-attachments/assets/02e54a9d-037a-4d59-8c86-a768167b4372)
![Screenshot 2024-12-10 124117](https://github.com/user-attachments/assets/b61ba614-3da0-4e94-a92d-ad0922a7c37e)
![Screenshot 2024-12-10 124104](https://github.com/user-attachments/assets/32308e55-c625-48e4-a2ee-47e6614850c4)

**Comment by Noob-dev21** [comment]
![image](https://github.com/user-attachments/assets/e1cd794b-42d6-4157-8d1d-69397443db92)

**Comment by Parik27** [comment]
Please ask questions about how to use Blender or help with making vehicles in discussions or in the Discord server (the link is in the readme). Issues should only be used for actual issues with the addon.

**Comment by Noob-dev21** [comment]
i apologize for my mistake, thank you for letting me know 

> Please ask questions about how to use Blender or help with making vehicles in discussions or in the Discord server (the link is in the readme). Issues should only be used for actual issues with the addon.
