### ISSUE TITLE
[Suggestion] Incorrect material name when importing dff

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#37]
When importing .dff to the editor, the list of superimposed materials on the model looks very strange, for example, if 2 materials (wall.png, stone.png) are applied to the object, then after importing to Blender they are called: cube.1, cube.2, .... cube.N (where cube is the name of the model and the number after that is the order of the material).
You may find it convenient, but today I had a mission to edit the finished dff from the game, and paste it back into the game with the edits, and I had to re-enter all the names of the textures in the names of materials.
Thank you for your work!

**Comment by Parik27** [comment]
What exactly do you mean by materials? The game has no names for materials, if you're referring to the texture names, the plug-in doesn't rename the texture names, it's up to Blender to name the textures if there are any duplicates (if you're importing only one model, it shouldn't be an issue). Furthermore, the add-on removes the extensions (that would include the suffixes Blender puts on them) when exporting the textures.

**Comment by Calvin-rgb** [comment]
I’ll try to explain: I have a model from the game in the .dff format, it has 2 textures (the names of these textures I mentioned above) with a specific name. When imported into the editor, it creates materials with these textures, only the materials themselves do not have the name of these child textures. I had a question: when exporting a model, should the material be called the same as the texture, or can it have any name?

**Comment by Parik27** [comment]
The material name doesn't matter, as I mentioned earlier, you can name it anything you want. The material name is not stored in the dff, which is why they're renamed to "cube.1" etc. 

The texture name is what matters, and I put careful thought on preserving the texture names during export. It's mentioned in the "Export Names" section on the wiki.

**Comment by Calvin-rgb** [comment]
You're right. I assumed that my model does not work for this reason, it turns out the reason is different. Need to read the wiki, thanks for the answer.
