### ISSUE TITLE
AttributeError: module 'gta.gui' has no attribute 'EXPORT_OT_col'

### ISSUE THREAD

**Issue by TinyJSDeveloper** [Parik27/DragonFF#38]
When trying to install and enable the most recent version from master, it gives me this error:

```
Traceback (most recent call last):
File ".../addon_utils.py", line 351, in enable
mod = __import__(module_name)
File ".../__init__py", line 37, in <module>
gui.EXPORT_OT_col,
AttributeError: module 'gta.gui' has no attribute 'EXPORT_OT_col'
```

Classes `EXPORT_OT_col` and `DFF_MT_ExportChoice` are not being imported. The Addon can be enabled with no errors after commenting these classes out on `__init__.py`:

```
# Class list to register
_classes = [
    gui.IMPORT_OT_dff,
    gui.EXPORT_OT_dff,
    # gui.EXPORT_OT_col,
    gui.MATERIAL_PT_dffMaterials,
    gui.OBJECT_PT_dffObjects,
    gui.DFFMaterialProps,
    gui.DFFObjectProps,
    gui.MapImportPanel,
    gui.DFFSceneProps,
    # gui.DFF_MT_ExportChoice,
    map_importer.Map_Import_Operator
]
```

**Comment by Parik27** [comment]
Well, it must be an error, Blender must've cached the script plug-ins.  You should try restarting Blender, if you didn't already. Those classes need to be registered in order to enable collision import/export.

**Comment by TinyJSDeveloper** [comment]
Restarting Blender after uninstalling the previous version resolved the problem. Thanks!
