### ISSUE TITLE
Exporting Problem

### ISSUE THREAD

**Issue by JagleW** [Parik27/DragonFF#40]
Hello,
I made a model for my GTA SA building and tried to export it using your plugin. When tried to install it into my MTA SA server my game just crashed and I didn't knew reason for it. But I tried to import previously exported .dff file also using this script and all cubes I scaled were just normal cubes, floating, without any scale. Why it isn't exporting scale parameters? Or maybe I am doing something wrong. I hope you'll help me.
Thanks.
![Screenshot_1](https://user-images.githubusercontent.com/44727277/83450622-e63aa580-a455-11ea-981c-f9a38dd51efa.png)
![Screenshot_2](https://user-images.githubusercontent.com/44727277/83450625-e76bd280-a455-11ea-8e49-7678c5e3b59c.png)

**Comment by Parik27** [comment]
I'm not sure about the crashing part, did you export the models with the correct parameters? 

About cubes not scaling, did you apply the scale before exporting?

**Comment by JagleW** [comment]
I'm sorry, but I am kind of new to modelling in Blender, we just want to make few simple '3D' building models to make our 'roleplay' cooler. Maybe crashes was because not applying texture into that model, but I don't know. I know how to apply textures onto models, i did it few times and it's not hard, that's not a thing. When I am importing an DFF using Your program the txd isn't loading and it have no textures. I checked the 'load txd file' and the txd is in the same location and have the same name as dff. When textures on basic unedited model will load I will just apply textures on thing I've just modified (garage entrance or whatever my "model" it is supposed to be) from textures that already exist in basic model.
Original model is not included in screenshots because I removed it hoping that it will help, but it isn't.

Again I am sorry for wasting your time, but there are no any tutorials or even videos when someone makes GTA SA models.

**Comment by JagleW** [comment]
And about that crashing; 
I also applied model into my game in which I only removed few things from it and didn't added anything. That file did not crashed my game.
I think is it fault at my side with exporting that model bad, but I don't know what I am doing wrong.

**Comment by JagleW** [comment]
I also applied the scale and transformation of that "thing" and now it is all good with scale. It's been fault of mine, but that's not mine only problem. I don't know what I am doing wrong with exporting it, so my game crashes.

**Comment by JagleW** [comment]
But why Your script is not importing textures into object. I think about that.
TXD been in the same location, had same name and I've checked load txd.

**Comment by Parik27** [comment]
The script can't load txd files at the moment. That's a feature planned for the future

**Comment by JagleW** [comment]
After some help by MTA-Team side I textured whole thing and now I am able to get this model loaded into the game without any crashes, but there are another problem. Collision file I've exported is corrupted, DFF too. (Second screen - how it shows in the game, first how it looks in Blender)
I am also attaching my; Blender project file, DFF I've exported, TXD from which I applied textures and exported COL, so you could help me easier. (on ZIP because github does not support txd,dff and blend.
![Screenshot_1](https://user-images.githubusercontent.com/44727277/83898272-fe147100-a756-11ea-995b-aa265d91b65b.png)
![Screenshot_2](https://user-images.githubusercontent.com/44727277/83898277-ff459e00-a756-11ea-9291-ab7e78d416ae.png)
[files.zip](https://github.com/Parik27/DragonFF/files/4737294/files.zip)

**Comment by JagleW** [comment]
Okay, so everything is fixed right now, model is working and everything is fine. But there's one last problem.  In latest DragonFF version downloaded from "releases" tab .col exporting function is not showing up when I try to export, so I downloaded that from "code" tab, that includes this function for 100%. When tried to load the addon I've got this error;
![image](https://user-images.githubusercontent.com/44727277/84180912-92007880-aa88-11ea-8578-8d03917b3ff5.png)

**Comment by Parik27** [comment]
Alright. good to know. Yeah, the latest release doesn't have the col exporting function. 

Regarding that error, you have to restart Blender for it to take effect. That's what worked for most people anyway.

**Comment by JagleW** [comment]
Okay, but .col file, that I've exported have 0B and when I'm installing it, objects that I've added to this model don't have collisions and that part of object, that existed in original game have collisions moved up. Also exporting DFF with option "export collision" throws error showed bellow;
![image](https://user-images.githubusercontent.com/44727277/84254554-accaff80-ab11-11ea-9bfa-6278bf0b379c.png)

**Comment by JagleW** [comment]
That's all, I think. Thank you for help. Have a nice day. Bye.
