### ISSUE TITLE
Exporting problem.

### ISSUE THREAD

**Issue by just-chris** [Parik27/DragonFF#47]
While exporting, material names won't save, this causes a problem with samp.

**Comment by ThePortuguesePlayer** [comment]
I think I read on the DFF file wiki that the file itself doesn't save material names, so, I'm pretty sure your problem is another.
Could you make a description of the problem you're having?

**Comment by revson1** [comment]
Yes, 
when i try to use model exported in DragonFF in SA-MP (Modifictaion) i get an error w that says
`Error(44007:0x5)

material and texture names must be 1-31 characters

materials are only allowed to have 1 texture assigned. alpha is done in the txd texture, there is no need to have multiple textures on a single material.`
Also, i cannot import models exported from DragonFF to another importer.
When i import models from other .dff plugin uv assigns aren't set properly, but when i import dff exported from DragonFF they are, but they don't have names that i gave them.
So i think there is problem in exporting DFF.

**Comment by revson1** [comment]
It actually seems like materials exported by DragonFF have no name at all, that may be why im getting that error.

**Comment by Parik27** [comment]
I'm not aware of any models that have the materials named :thinking: Could you send a sample where one does?

**Comment by revson1** [comment]
Here, its from another exporter.
[good.zip](https://github.com/Parik27/DragonFF/files/4962316/good.zip)

**Comment by revson1** [comment]
I think this is also the problem why you can't import DragonFF to kam's scripts on 3ds max.

**Comment by Parik27** [comment]
The good model doesn't have any name on the material. It does have two textures though. As the error message states, you don't need to have two textures on the same model. I'm not sure how the error doesn't show for the model you sent me though. DragonFF shouldn't try to export more than one texture anyway. Also ensure that the texture names are not too long according to the error message as well.

**Comment by revson1** [comment]
Yes, but models exported with KAMS work with samp, and models exported with DragonFF sadly don't. Im looking forward for this to be fixed. If you want, i can send You the source code of exporter that works well, but it exports only one texture.

**Comment by revson1** [comment]
Also, if i just import and export skin using DragonFF (without changing anything) it still gives that error. When i use freshly imported model from gta3.img it doesn't.
