### ISSUE TITLE
Siatka DFF

### ISSUE THREAD

**Issue by MrYooGi** [Parik27/DragonFF#48]
Witam jak w Blender mieć wiele Śiatek podłączonych do skina bo jak wgrywam skina to mi tylko jedna wyświetla na skinie.

**Comment by revson1** [comment]
Pewnie skin jest wzięty z innego exportera, a DragonFF używa innego "typu" plików .dff. Jedynym rozwiązaniem jest ręczne aplikowanie siatki.
