### ISSUE TITLE
Error exporting DFF with bump maps

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [Parik27/DragonFF#51]
![image](https://user-images.githubusercontent.com/47691365/92018621-48ed5700-ed4d-11ea-9488-59c064388e83.png)

![image](https://user-images.githubusercontent.com/47691365/92018712-66babc00-ed4d-11ea-9495-ae7e5f7f59a9.png)

I have to complain about the documentation here, because I can't even be sure if I'm doing this right. The documentation for the Materials is short on information and the one it has is based on loose terms that leaves you wondering if you understood it right.
I have yet to understand what the Framebuffer Alpha is used for in the Env Maps section, or, if the Bump Map the game uses is a black and white map or a RGB normal map (the purple ones with red, green and blue creeping in places). Also, certain information, for example, about the Environment Map not using any texture in PC and Xbox seems to be straight incorrect. I'm talking about this piece of text:
![image](https://user-images.githubusercontent.com/47691365/92019467-93230800-ed4e-11ea-8f42-04e536c98d4c.png)
I've tested this ingame, and, the game does in fact use the texture stated there (scrolling it as you move), and, if removed, the material turns simply black.

With that out of the way, is this error on export due to a bad setup or an actual bug? I tried to follow the documentation on it as best as I could understand it.
Also, by "Diffuse Texture", you mean the texture used as material color? An RGB normal map (and thus not a diffuse texture)? The "_B" hint me this is in fact a bump map... Could you show an example?
![image](https://user-images.githubusercontent.com/47691365/92020050-776c3180-ed4f-11ea-8423-0aa41551dcfb.png)

**Comment by Parik27** [comment]
That appears to be an issue with the exporter, yeah. Your setup seems correct, I'll take a look. 

I understand your points about the documentation, it was written for mainly people already familiar with the material effects. You shouldn't need to understand all of it to make use of it. Also yes, diffuse texture means the normal map, I'll edit it.

**Comment by Parik27** [comment]
Thanks for the report. The "Diffuse Texture" is the "Height Map". You can either have a bump map or a height map in the Bump Map Effect PLG. The Normal map in the nodes will be the "Bump Map" and the texture name in the settings will be the Height Map.

About animation support, there's no plans for it at the moment, since I'll mostly be focusing on perfecting the model aspects of the addon.
