### ISSUE TITLE
With export distorts the model

### ISSUE THREAD

**Issue by NeXt2k19** [Parik27/DragonFF#53]
Hey,
As in the subject, when I import dff, I have such a strange thing with the object.

![123](https://user-images.githubusercontent.com/52257187/93026275-31dc1e00-f605-11ea-89ad-1ec1de1093a5.PNG)
![321](https://user-images.githubusercontent.com/52257187/93026276-330d4b00-f605-11ea-88ba-2f934d063981.PNG)

**Comment by NeXt2k19** [comment]
Does anyone know?

**Comment by Parik27** [comment]
Can't say for sure without looking at the geometry and export options
