### ISSUE TITLE
Bug UV-map with imported DFF model 

### ISSUE THREAD

**Issue by Calvin-rgb** [Parik27/DragonFF#54]
I imported the DFF model into blender and for some reason the UV map of the road has the wrong coordinates (screenshot attached). The screenshot shows that the texture of the polygon is incorrectly mapped, I think this is due to inaccurate import of the UV map.

**If you think that this is a model problem, then it is not, everything is displayed correctly in 3ds max.**
![Screen](https://imgur.com/z7BAcsq.png)

**Comment by Calvin-rgb** [comment]
Here is a normal UV map before importing into blender
![](https://imgur.com/Yl4LQNI.png)

**Comment by Parik27** [comment]
Did you check if the UV-mapping is incorrect in Blender after importing? You seem to have posted a screenshot in-game and not in Blender itself. 

I won't be able to tell much without examining the model myself.

**Comment by Calvin-rgb** [comment]
@Parik27 
![](https://imgur.com/SQ3En64.png)

**Comment by Calvin-rgb** [comment]
I imported DFF, edited a couple of points, and exported. And such a problem was discovered. The second screen was made in MTA where the original model was without problems. Editing was not related to UV maps, so I guess this is an importer problem

**Comment by Parik27** [comment]
Well, this is still not enough data to work with. The importer works fine for most models. Did you try to import and simply export the model? "Editing was not related to UV maps" - since you said a couple of points ( I assume vertices), you seem to have changed the mesh, which *can* change how the UV maps to the model.

**Comment by Calvin-rgb** [comment]
I did not rule this section in any way, the script imported it like that. Can I drop the source for you, and you import it and look at the problem?

**Comment by Parik27** [comment]
Sure, yeah. That'd be helpful

**Comment by Calvin-rgb** [comment]
This model is in its original form, import it into blender to see the problem.
![google.disk](https://drive.google.com/file/d/1NC4tqzrPaWUodEy3yd_3fDu5WcLEVHys/view?usp=sharing)

**Comment by Parik27** [comment]
Seems to be fine here -

![](https://cdn.discordapp.com/attachments/682894128530456587/764891294467358760/unknown.png)

**Comment by Calvin-rgb** [comment]
I've just imported the model and it's surprisingly fine. This is very strange since the first time I noticed the UV problem in 3 places on the model, now everything is fine. Is the problem in my computer then?
