### ISSUE TITLE
Texture Import Problem

### ISSUE THREAD

**Issue by NeXt2k20** [Parik27/DragonFF#60]
Hi,
I imported the character to Blender and turned it on to show textures because he wanted to make a Render, but the character is only pink, I don't know what's going on, I never had that, there was never a problem on this character before.
Please help.

![Przechwytywanie](https://user-images.githubusercontent.com/74677585/99570849-d4809680-29d2-11eb-8157-aeb88fbb03fd.PNG)

**Comment by Parik27** [comment]
Did you extract the textures from the txd file? The txd file import is not yet finished, so it's unable to export them on its own.

**Comment by NeXt2k20** [comment]
This is how I separated them all, please take a look:
![Przechwytywanie](https://user-images.githubusercontent.com/74677585/99917797-d750f380-2d12-11eb-8206-0d6621134bb1.PNG)

**Comment by Parik27** [comment]
Check "Read Material Split" in the import options while importing. I assume this is a model exported by KAMS, which doesn't set the materials properly.
