### ISSUE TITLE
import wheels?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#70]
how do I make the sa vehicle import all of the wheels? I only get one (RF). It imports the dummies but when I try to align the wheels by duplicating them and position them to the dummy, it does not look correct

**Comment by umustbeloggedintododat** [comment]
hello?

**Comment by Parik27** [comment]
SA vehicles don't normally have 4 wheels, they have 1 wheel that's duplicated for all of the other wheels. If you want to get all 4 wheels, you'll have to place them manually.
