### ISSUE TITLE
map does not come complete

### ISSUE THREAD

**Issue by Nicolas3Ds** [Parik27/DragonFF#76]
When will there be the update that allows the map to be imported, because in this version the map does not come complete

**Comment by Izzotop** [comment]
@Nicolas3Ds Which game map you want to import and why the map is incompleteness?

**Comment by Nicolas3Ds** [comment]
> @ Nicolas3Ds Qual mapa do jogo você deseja importar e por que o mapa está incompleto?

I'm importing the Lan from gta sa, but only the game lods come or a large part is missing

**Comment by Nicolas3Ds** [comment]
![image](https://user-images.githubusercontent.com/79784185/109433772-e4a40b00-79f0-11eb-805f-e6acfebd16ba.png)


> @Nicolas3Ds Which game map you want to import and why the map is incompleteness?

**Comment by Izzotop** [comment]
**LAn.IPL** has 162 entries and 119 of them are LOD's.


You can see that output in system console. (Edit -> Menu Search -> Toggle System Console)
```
MapDataUtility reading: C:\Games\GTA San Andreas Build 36c\DATA\MAPS\LA\LAn.IPL
inst: 162 entries
grge: 2 entries
enex: 4 entries
pick: 0 entries
jump: 0 entries
```

![image](https://user-images.githubusercontent.com/1680033/109913830-b90a7480-7cbf-11eb-9cd5-bf3a4079faa5.png)

**Comment by Nicolas3Ds** [comment]
> **LAn.IPL** tem 162 entradas e 119 delas são LODs.
> 
> Você pode ver essa saída no console do sistema. (Editar -> Pesquisa de menu -> Alternar console do sistema)
> 
> ```
> MapDataUtility reading: C:\Games\GTA San Andreas Build 36c\DATA\MAPS\LA\LAn.IPL
> inst: 162 entries
> grge: 2 entries
> enex: 4 entries
> pick: 0 entries
> jump: 0 entries
> ```
> 
> ![imagem](https://user-images.githubusercontent.com/1680033/109913830-b90a7480-7cbf-11eb-9cd5-bf3a4079faa5.png)
thank you i will close the report
