### ISSUE TITLE
mob skin export bug in blender 2.8 and higher

### ISSUE THREAD

**Issue by kacper299** [Parik27/DragonFF#77]
hi, it's problem witch export gta sa mob skins, in blender 2.8 and newer versions. Textures are randomly transparent on one side in the part's of models. It's any way to fix this? or only using older version of blender? Will show up any update DragonFF to working well witch new blender?

**Comment by kacper299** [comment]
screen (look this hair);
![image](https://user-images.githubusercontent.com/77008351/109421318-114b2900-79d7-11eb-9192-118ae571f868.png)

**Comment by Parik27** [comment]
Looks like backface culling, can't tell if it's any other issue just from the screenshots. Try adding depth to the polygons and see if that fixes the issue.

**Comment by kacper299** [comment]
I coped with this problem, thanks for your help.
