### ISSUE TITLE
col file doesn't matter at all

### ISSUE THREAD

**Issue by Nicolas3Ds** [Parik27/DragonFF#78]
I tried to import an original game crash but when I try it is missing parts

![image](https://user-images.githubusercontent.com/79784185/109893241-12e04f80-7c6a-11eb-90c6-cfffdce6bdbf.png)

In the COL editor  appears normal

![image](https://user-images.githubusercontent.com/79784185/109893304-2ab7d380-7c6a-11eb-8d65-a65b2f8ef613.png)

**Comment by Izzotop** [comment]
Thank you for reporting. As i can see, collision importer doesn't support boxes. Collision/Shadow mesh and spheres are supported at current moment.

![image](https://user-images.githubusercontent.com/1680033/109915395-d42ab380-7cc2-11eb-9bf0-040528c02c4c.png)

**Comment by Nicolas3Ds** [comment]
> Obrigado por relatar. Como posso ver, o importador de colisão não suporta caixas. Malha de colisão / sombra e esferas são suportadas no momento atual.
> 
> ![imagem](https://user-images.githubusercontent.com/1680033/109915395-d42ab380-7cc2-11eb-9bf0-040528c02c4c.png)

Is there any way I can solve this because I'm messing with an original one making minigames for MTA, and the bug collision when the 3D object is used, and exported

**Comment by jgooderham** [comment]
I've addressed this issue in #316
