### ISSUE TITLE
Re-assigning bones (via armature - automatic weights) breaks export

### ISSUE THREAD

**Issue by UJIbU4** [Parik27/DragonFF#87]
Hi! Trying edit a character (replace bones from one model to another).
When removing all vertex groups of the mesh and then re-parenting bones with mesh via armature deform with automatic weights (to create new vertex groups) the model becomes unexportable (IndexError: list assignment index out of range). Even when trying to do these steps with model's own bones.

**Comment by Parik27** [comment]
Hi,

Can't say for sure without the blend file and the complete error.

**Comment by UJIbU4** [comment]
Uploaded here https://dropmefiles.com/O2gFO

**Comment by UJIbU4** [comment]
Error: https://ibb.co/p2mvcvv

**Comment by Parik27** [comment]
It exports fine for me on the latest version (the git trunk). 

Also note Blender 2.79 isn't supported by the addon, so you're likely to run into issues if you try to use it there. The latest version of Blender is already 2.92, so maintaining two versions of the Blender addon is really difficult at this point.

**Comment by UJIbU4** [comment]
Confirmed, thanks for help.
