### ISSUE TITLE
Map import not working for GTA VC

### ISSUE THREAD

**Issue by Gamination** [Parik27/DragonFF#89]
happens while loading washintn, washints, oceandrv, oceandn, airport(N)
https://cdn.discordapp.com/attachments/787710009089589261/839388569050021898/unknown.png

**Comment by Parik27** [comment]
That's an old version of DragonFF, you should get the latest version by downloading the latest master branch (not releases).

[Here](https://github.com/Parik27/DragonFF/archive/refs/heads/master.zip)
