### ISSUE TITLE
Objects have problems with prelights (vertex colors) 

### ISSUE THREAD

**Issue by Skyliner77** [Parik27/DragonFF#91]
̶O̶t̶h̶e̶r̶ ̶m̶u̶l̶t̶i̶p̶l̶e̶ ̶o̶b̶j̶e̶c̶t̶s̶ ̶w̶i̶t̶h̶ ̶t̶h̶e̶ ̶s̶a̶m̶e̶ ̶s̶e̶t̶t̶i̶n̶g̶s̶ ̶w̶o̶r̶k̶i̶n̶g̶ ̶b̶u̶t̶ ̶t̶h̶i̶s̶ ̶o̶n̶e̶ ̶h̶a̶s̶ ̶i̶s̶s̶u̶e̶s̶,̶ ̶p̶l̶e̶a̶s̶e̶ ̶t̶a̶k̶e̶ ̶a̶ ̶l̶o̶o̶k̶ ̶i̶f̶ ̶y̶o̶u̶ ̶c̶a̶n̶.̶ ̶
̶[̶l̶i̶n̶k̶]̶(̶h̶t̶t̶p̶s̶:̶/̶/̶d̶r̶i̶v̶e̶.̶g̶o̶o̶g̶l̶e̶.̶c̶o̶m̶/̶f̶i̶l̶e̶/̶d̶/̶1̶H̶-̶9̶U̶s̶y̶U̶u̶q̶A̶K̶h̶c̶X̶N̶o̶M̶h̶l̶l̶r̶s̶n̶P̶l̶h̶w̶I̶J̶P̶S̶y̶/̶v̶i̶e̶w̶?̶u̶s̶p̶=̶s̶h̶a̶r̶i̶n̶g̶)̶
Updated info down below.

**Comment by Skyliner77** [comment]
Update: More info on the issue, to be more specific, models extracted from the GTA:SA acts weird, while MEd doesn't see a model, Col editor shows this message "No embedded collision object found, and no dff mesh import available yet" yet blender perfectly re-imports the same file with no issues. Tried several export settings - nothing seems to work so far, copying model mesh/appending to new.blend file doesn't seem to work either. Deleted all textures and model, then created default cube - MEd straight up crashed, I have no f idea whats going on. Can provide all available info if someone curious to help.

**Comment by Skyliner77** [comment]
Huh, now this error pops up: 
![image](https://user-images.githubusercontent.com/75580678/119238546-9f086180-bb4b-11eb-891b-6a8c21f5624f.png)

**Comment by Skyliner77** [comment]
Ok so after countless hours trying to solve this problem I've moved on to learn how to add pre-light to the model only to understand that vertex colors were causing this problem all along. Idk if the "export vertex colors" feature is broken or not, gonna try to figure out how to fix it, or use it correctly. Lack of documentation really kicks below the belt on this one.
Until then if you're customizing map models from the original GTA:SA, go to "Object Data Properties" open "Vertex Colors" and remove all colors, (Col; Col001). That should fix the problem with import in MEd and GTA:SA in general. 
![image](https://user-images.githubusercontent.com/75580678/119364708-d562ef80-bcb7-11eb-8a52-8accc38fa33f.png)

**Comment by Skyliner77** [comment]
Huh turns out DeagonFF has a wiki, anyway following wiki instructions (https://github.com/Parik27/DragonFF/wiki/Creating-vertex-color-groups) doesn't work for me either, tried falling back on blender 2.8, same results. Welp to the long drawer you go vertex colors bug, if someone comes across this post I kindly asking you to try it out yourself and give me the results, any feedback would be appreciated.

**Comment by Parik27** [comment]
The error you posted is pretty clear, it was probably opened in a different program or it didn't have permissions to write.

Regardless, issues with imports in MEd/other similar DFF viewers are bugs in MEd, not DragonFF. The exported dff should work in-game regardless. Your findings about it being related to vertex colours seem interesting. Previously, such an issue was resolved by enabling Bin Mesh PLG in the options. 

It's probably not a good solution to disable vertex colours since they're used for prelighting map objects, so removing them is probably not a good idea. Not sure what you mean by vertex colours not working, I assume you mean they don't work in MEd?

**Comment by Parik27** [comment]
Yeah, I looked further into the issue - it is indeed an MEd bug.

It expects the Night Vertex Colour extension to be after the Bin Mesh PLG extension, so... ask MEd developers to fix that. :)

**Comment by Skyliner77** [comment]
Huh, tested it myself - it worked just fine, thanks for your time. Going to update info on wiki to avoid suffering of other souls.
