### ISSUE TITLE
Mismatched colors on vehicle parts

### ISSUE THREAD

**Issue by vbaptistella** [Parik27/DragonFF#93]
I converted a car from GTA 3 to SA and used all the materials from an imported car from SA

It looks right on Blender, but in-game the body color is different from the other parts, even though they are using the same material (primary)

Black is the most affected color by this issue:
![image](https://user-images.githubusercontent.com/25177034/119767751-d77ea700-be8d-11eb-9269-88a803869500.png)

Other colors suffer as well, but in a smaller scale:
![image](https://user-images.githubusercontent.com/25177034/119767849-0d239000-be8e-11eb-85c2-4e7eccd691d2.png)
![image](https://user-images.githubusercontent.com/25177034/119767930-2b898b80-be8e-11eb-9346-1541f3958015.png)

In Blender:
![image](https://user-images.githubusercontent.com/25177034/119768023-5378ef00-be8e-11eb-90c4-ce37861a5097.png)
![image](https://user-images.githubusercontent.com/25177034/119768062-5ffd4780-be8e-11eb-852c-ffbdc1589cb4.png)
![image](https://user-images.githubusercontent.com/25177034/119768082-6986af80-be8e-11eb-8536-c3338fe951bc.png)

**Comment by Parik27** [comment]
Doesn't seem to look right in Blender either - the doors don't seem to have a texture. Cars in SA use a dirt texture/reflection map as well (using a second UV map).

**Comment by vbaptistella** [comment]
That's just because i didn't align the doors texture with the body, so it is on the part without the dirt

Moving the UV a bit shows the dirt:
![image](https://user-images.githubusercontent.com/25177034/119799662-abc1e800-beb2-11eb-81a2-7f99e8769c5c.png)

**Comment by Parik27** [comment]
Make sure that the environment map UV mapping (the second UV map) is also aligned with the body then.

**Comment by Skyliner77** [comment]
1st check your environmental map, maybe it is misaligned. The second UV map layer is responsible for it, so make sure it's evenly stretched across the whole car. 
**Correctly aligned environmental map**
In blender:
![image](https://user-images.githubusercontent.com/75580678/119894118-e2484300-bf44-11eb-9023-64cf34b7c7d8.png)
You might want to open the reference image manually (xvehicleenv128.png)
![image](https://user-images.githubusercontent.com/75580678/119894886-da3cd300-bf45-11eb-8ba9-1feda52fe5bb.png)
In-game: 
![image](https://user-images.githubusercontent.com/75580678/119893877-95fd0300-bf44-11eb-9cc7-7109916126c8.png)
**Badly aligned environmental map**
In blender:
![image](https://user-images.githubusercontent.com/75580678/119894996-f6d90b00-bf45-11eb-8f0a-0eaa461e9f73.png)
In-game:
![image](https://user-images.githubusercontent.com/75580678/119895040-022c3680-bf46-11eb-921b-03f4236956b3.png)
2nd normals orientation may be wrong
 To check this you must turn on face orientation in the viewport menu: 
![image](https://user-images.githubusercontent.com/75580678/119895398-64853700-bf46-11eb-9bda-0148021cb9ff.png)
Normals orientation must always be against facing texture (outside), simply - correct facing = blue, wrong = red (not always) 
Wrong normals facing in blender:
![image](https://user-images.githubusercontent.com/75580678/119896069-318f7300-bf47-11eb-97ae-4445a4de7d75.png)
In-game:
![image](https://user-images.githubusercontent.com/75580678/119896151-479d3380-bf47-11eb-86a1-b0f6895c0960.png)
To fix wrong normals, go to edit mode, select part of the object with wrong faces (shouldn't be 100% accurate) and hit CNTRL+SHIFT+N to call the recalculation menu and simply check/uncheck the "inside" option box.
![image](https://user-images.githubusercontent.com/75580678/119896458-b8445000-bf47-11eb-9354-8d6321fdb9bf.png)
Or check precisely all wrong faces, go to the Mesh -> Normals and choose "Flip" option. (Or press CNTRL+N i customised my binding keys so I don't remember if this shortcut default or not)

**Comment by vbaptistella** [comment]
Realigning the second UV map solved the issue, thanks!
![image](https://user-images.githubusercontent.com/25177034/119919631-351ffb80-bf41-11eb-9782-61a4a0ceb575.png)
