### ISSUE TITLE
Corrupted model import

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Parik27/DragonFF#94]
I imported the GM TDH-5303 bus mod and this happened.
![brokenaaa](https://user-images.githubusercontent.com/54049600/120103275-de6f1900-c11c-11eb-9319-8d0acdd0bfa0.PNG)
Can you look into it? I unchecked and checked the various boxes and nothing happened at all.
https://www.gtainside.com/en/sanandreas/cars/13506-1969-gm-tdh-5303-bus-v1-0/

**Comment by Skyliner77** [comment]
I think it has something to do with resetting location/rotation/scale to Deltas, it messes up the model in blender somehow, I'm currently working on a map and I reset scale to deltas by accident, now some objects in-game bigger than they are in blender and vice versa when importing dff file. It could be that or the author simply run the model thru some sort off .dff protections software.

**Comment by umustbeloggedintododat** [comment]
I think it's the former one, since it was a model made back in 2007. DFF protection was not common (at all) in the early 2000s.

**Comment by umustbeloggedintododat** [comment]
Having this issue with the nissan patrol model:
https://www.gtainside.com/en/sanandreas/cars/91428-nissan-patrol-y61-off-road/
